### ISSUE TITLE
unable to access container on swarm overlay network

### ISSUE THREAD

**Issue by pdhamdhere** [vmware/photon#610] opened 2017-02-23 23:24 UTC
Setup 3 VMs with following additional configuration:
- Docker Engine: 1.13.1
```
docker info
...
Server Version: 1.13.1
...
```
- IP tables disabled

```
iptables --list
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination 
```

- Created Swarm cluster with `docker swarm init` & `docker swarm join`
```
docker node ls
ID                           HOSTNAME          STATUS  AVAILABILITY  MANAGER STATUS
iykwsutimhvl0ubebuegg1nfk    Photon-3          Ready   Active        
nym93czz0j5ixyrx01ze9hwbu *  photon-CMnLHnmTk  Ready   Active        Leader
q8yjttpogfikmqhddohnawrex    photon-MAmlQtafC  Ready   Active        
```

- Deploy nginx app
```
cat nginx-stack.yaml
version: "3"

services:

  nginx:
    image: nginx
    ports:
      - "5000:80"

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
```

- Deploy above compose file
```
docker stack deploy -c nginx-stack.yaml ng

docker stack ps ng                        
ID            NAME        IMAGE         NODE              DESIRED STATE  CURRENT STATE           ERROR  PORTS
iu8kxy6i4xnq  ng_nginx.1  nginx:latest  photon-CMnLHnmTk  Running        Running 19 minutes ago         
```
nginx container is scheduled on master node with IP 172.16.111.130

```
curl 172.16.111.130:5000
curl: (7) Failed to connect to 172.16.111.130 port 5000: Connection refused
```

Additional info:
```
docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
b6ded3faf72c        bridge              bridge              local
0d2a452478e3        docker_gwbridge     bridge              local
c2036171e2e8        host                host                local
lcmy16zrvytj        ingress             overlay             swarm
a7ik1coh22nm        ng_default          overlay             swarm
58dfb88e9229        none                null                local

ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:0c:29:65:2c:f4 brd ff:ff:ff:ff:ff:ff
    inet 172.16.111.130/24 brd 172.16.111.255 scope global dynamic eth0
       valid_lft 1031sec preferred_lft 1031sec
    inet6 fe80::20c:29ff:fe65:2cf4/64 scope link 
       valid_lft forever preferred_lft forever
3: docker_gwbridge: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:5e:7a:58:5c brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.1/16 scope global docker_gwbridge
       valid_lft forever preferred_lft forever
    inet6 fe80::42:5eff:fe7a:585c/64 scope link 
       valid_lft forever preferred_lft forever
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:f0:13:de:24 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:f0ff:fe13:de24/64 scope link 
       valid_lft forever preferred_lft forever
10: vethed529ea@if9: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker_gwbridge state UP group default 
    link/ether 3e:0e:fe:9f:a1:6b brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::3c0e:feff:fe9f:a16b/64 scope link 
       valid_lft forever preferred_lft forever
115: vethb8d0a15@if114: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker_gwbridge state UP group default 
    link/ether 66:74:62:1d:a3:0b brd ff:ff:ff:ff:ff:ff link-netnsid 8
    inet6 fe80::6474:62ff:fe1d:a30b/64 scope link 
       valid_lft forever preferred_lft forever
```

`docker stack deploy -c nginx-stack.yaml ng` worked on ubuntu with no hiccups.

**Comment by pdhamdhere** [comment] 2017-02-23 23:25
CC/ @msterin @lipingxue @shuklanirdesh82

**Comment by YustasSwamp** [comment] 2017-04-19 08:11
Trying to reproduce it.
Can you provide an instruction for all three VMs, what commands to run there from empty VM to "curl: (7) Failed to connect to 172.16.111.130 port 5000: Connection refused", please?

**Comment by kaushik229** [comment] 2017-04-19 22:45
Ok, so I tried this on latest photon dev iso with docker version 1.13.1 and able to issue curl on port 5000 and get proper reply.
What i did different here is,
I added all ports related to docker swarm as mentioned at docker guide.

"https://docs.docker.com/engine/swarm/swarm-tutorial/#open-protocols-and-ports-between-the-hosts"

Using following commands,
iptables -I INPUT 4 -p tcp --dport 2376 -j ACCEPT
iptables -I INPUT 5 -p tcp --dport 2377 -j ACCEPT
iptables -I INPUT 6 -p tcp --dport 7946 -j ACCEPT
iptables -I INPUT 7 -p udp --dport 7946 -j ACCEPT
iptables -I INPUT 8 -p udp --dport 4789 -j ACCEPT
iptables -A INPUT  -p 50 -j ACCEPT
iptables -A OUTPUT -p 50 -j ACCEPT

I think you deleted all rules using iptables in your experiment which probably deleted all docker chains rules too. I suspect this may be the issue here, because when I did iptables --list on my setup, I can see these extra docker chain rules.

Chain FORWARD (policy DROP)
target     prot opt source               destination         
DOCKER-INGRESS  all  --  anywhere             anywhere            
DOCKER-ISOLATION  all  --  anywhere             anywhere            
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere            
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
DROP       all  --  anywhere             anywhere            

Chain OUTPUT (policy DROP)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     esp  --  anywhere             anywhere            

Chain DOCKER (2 references)
target     prot opt source               destination         

Chain DOCKER-INGRESS (1 references)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:commplex-main
ACCEPT     tcp  --  anywhere             anywhere             state RELATED,ESTABLISHED tcp spt:commplex-main
RETURN     all  --  anywhere             anywhere            

Chain DOCKER-ISOLATION (1 references)
target     prot opt source               destination         
DROP       all  --  anywhere             anywhere            
DROP       all  --  anywhere             anywhere            
RETURN     all  --  anywhere             anywhere         


Docker command logs for your reference from my setup.

MANAGER ====>

root@manager1 [ ~ ]# 
root@manager1 [ ~ ]# docker node ls
ID                           HOSTNAME  STATUS  AVAILABILITY  MANAGER STATUS
h5nu9v3mn18ypdwh0l2dfifw1 *  manager1  Ready   Active        Leader
hopoh5o6trkl5us4bfak499k1    worker1   Ready   Active        
zm291ytmuyk1tvxjmjpssl3sy    worker2   Ready   Active        
root@manager1 [ ~ ]# 
root@manager1 [ ~ ]# 
root@manager1 [ ~ ]# 
root@manager1 [ ~ ]# 
root@manager1 [ ~ ]# docker stack ps ng 
ID            NAME        IMAGE         NODE      DESIRED STATE  CURRENT STATE           ERROR  PORTS
uhizwcq75xvm  ng_nginx.1  nginx:latest  manager1  Running        Running 20 minutes ago         
root@manager1 [ ~ ]# 
root@manager1 [ ~ ]# 
root@manager1 [ ~ ]# 
root@manager1 [ ~ ]# curl 10.118.100.208:5000
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
root@manager1 [ ~ ]# 
root@manager1 [ ~ ]# docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
a921b65ba4ec        bridge              bridge              local
ab2c8b6d023e        docker_gwbridge     bridge              local
c7215d0c6ce5        host                host                local
u5aqtrwf3oia        ingress             overlay             swarm
xb9gbxzwwnyz        ng_default          overlay             swarm
a8bc38ba9e5a        none                null                local
root@manager1 [ ~ ]# 
root@manager1 [ ~ ]#


WORKER ===========>
root@worker1 [ ~ ]# curl 10.118.100.208:5000
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
root@worker1 [ ~ ]# 
root@worker1 [ ~ ]# 
root@worker1 [ ~ ]# 


Please let us know if this helps or not.

Thanks,
Kaushik

**Comment by pdhamdhere** [comment] 2017-04-20 19:00
Thanks, @kaushik229 for taking a look.

I had IP tables disabled **before** setting up Swarm cluster. Specific steps (IIRC) were;
1. Bring up 3 Photon VMs with latest OVAs
2. Disable IP tables
3. Update Docker to 1.13 using instruction from #508 
4. Setup Swarm(mode) cluster 

I changed my dev setup from Photon to Ubuntu long time back due to lack of response on this issue.  I'll definitely give new ISO a try when it is released. Thanks!

**Comment by sharathjg** [comment] 2017-04-21 21:18
was fixed with commit https://github.com/vmware/photon/commit/679fab3ca01d38049c582a5c96d2f04887e4aaf1

**Closed by sharathjg** 2017-04-21 21:18 UTC

**Comment by wjma90** [comment] 2018-11-29 23:55
I solved it using an earlier version of "boot2docker". Apparently version 18.09 has problems.

docker-machine create -d hyperv --hyperv-virtual-switch "myswitch" --hyperv-boot2docker-url=https://github.com/boot2docker/boot2docker/releases/down
load/v18.05.0-ce/boot2docker.iso myvm1

I have tested this solution with virtualbox driver (in mac) and with hyper-v (obviously windows)
