### ISSUE TITLE
SMB/CIFS 2 & 3 is broken

### ISSUE THREAD

**Issue by muhfugen** [vmware/photon#717] opened 2017-12-09 10:24 UTC
In Photon 1.0 you could pass the `vers` option to `mount` to specify the version of the SMB/CIFS protocol used. In Photon 2.0 you can no longer do so, it simply gives the error `mount error(22): Invalid argument` when this parameter is passed. I'm not intimately familiar with what actually goes on, but afaik there are two packages responsible for mounting SMB/CIFS shares - cifs-utils and the kernel.

I've tried downloading and building fro source cifs-utils-6.4 and 6.7 from Samba's website, but the problem remains, so i'm assuming this problem lays somewhere in the kernel.

This issue is problematic as for whatever reason the kernel is incapable of mounting a SMB/CIFS share from a Microsoft Scale Out File Server cluster unless `vers=2.0` is specified. `vers=3.0` used to work on Photon 1.0 but a kernel update broke it.

**Comment by YustasSwamp** [comment] 2017-12-12 07:44
can you show `uname -a` for both cases (working 1.0 and broken 2.0), please?

**Comment by muhfugen** [comment] 2017-12-12 10:55
@YustasSwamp 1.0 was always broken, even on other appliances such as Cisco Firepower Management Center (kernel 3.10.53) and APC NetBotz it refuses to mount under CIFS 1.0. I'm not sure why, on the SOFS cluster it shows that 1.0 is enabled:

```
PS C:\Users\Administrator.BIXNOOD> Get-SmbServerConfiguration | Select-Object -Property EnableSMB1Protocol

EnableSMB1Protocol
------------------
              True
```

**Photon 1.0 fresh install, CIFS 1.0 is broken, 3.0 works. After updating to kernel 4.4.103-1.ph1, CIFS 3.0 becomes broken, 2.0 still works:**
```
root@photon-7a1741e5b2c8 [ ~ ]# tdnf install cifs-utils

Installing:
libcap-ng                       x86_64      0.7.7-4.ph1          71.77 k
cifs-utils                      x86_64      6.4-2.ph1            51.28 k

Total installed size: 123.05 k
Is this ok [y/N]:y

Downloading:
cifs-utils                               32433    100%
libcap-ng                                28838    100%
Testing transaction
Running transaction

Complete!
root@photon-7a1741e5b2c8 [ ~ ]# mkdir /tmp/sofs.ad.bixnood.net
root@photon-7a1741e5b2c8 [ ~ ]# mount -t cifs -o vers=1.0,credentials=/root/.linux\@ad.bixnood.net //sofs.ad.bixnood.net/Linux /tmp/sofs.ad.bixnood.net/
mount error(13): Permission denied
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
root@photon-7a1741e5b2c8 [ ~ ]# mount -t cifs -o vers=3.0,credentials=/root/.linux\@ad.bixnood.net //sofs.ad.bixnood.net/Linux /tmp/sofs.ad.bixnood.net/
root@photon-7a1741e5b2c8 [ ~ ]# uname -a
Linux photon-7a1741e5b2c8 4.4.8 #1-photon SMP Tue Jun 7 08:04:49 UTC 2016 x86_64 GNU/Linux
root@photon-7a1741e5b2c8 [ ~ ]# tdnf clean all
Cleaning repos: lightwave photon photon-updates photon-extras
Cleaning up everything
root@photon-7a1741e5b2c8 [ ~ ]# tdnf upgrade linux

Upgrading:
initramfs                       x86_64      1.0-8.112903681.ph1  11.21 M
linux                           x86_64      4.4.103-1.ph1        21.98 M

Total installed size: 33.19 M
Is this ok [y/N]:y

Downloading:
linux                                 18866937    100%
initramfs                             11734379    100%
Testing transaction
Running transaction

Complete!
root@photon-7a1741e5b2c8 [ ~ ]# shutdown -r now
Connection to 192.168.144.133 closed by remote host.
Connection to 192.168.144.133 closed.
MacBookPro:~ admin$ ssh root@192.168.144.133
Password: 
Last login: Tue Dec 12 10:42:17 2017 from 192.168.144.1
root@photon-7a1741e5b2c8 [ ~ ]# mkdir /tmp/sofs.ad.bixnood.net
root@photon-7a1741e5b2c8 [ ~ ]# mount -t cifs -o vers=3.0,credentials=/root/.linux\@ad.bixnood.net //sofs.ad.bixnood.net/Linux /tmp/sofs.ad.bixnood.net/
mount error(5): Input/output error
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
root@photon-7a1741e5b2c8 [ ~ ]# mount -t cifs -o vers=2.0,credentials=/root/.linux\@ad.bixnood.net //sofs.ad.bixnood.net/Linux /tmp/sofs.ad.bixnood.net/
root@photon-7a1741e5b2c8 [ ~ ]# uname -a
Linux photon-7a1741e5b2c8 4.4.103-1.ph1 #1-photon SMP Thu Dec 7 03:17:17 UTC 2017 x86_64 GNU/Linux
```

**Photon 2.0, CIFS 1.0/2.0/3.0 are all broken:**
```
root@photon [ ~ ]# mkdir /tmp/sofs.ad.bixnood.net
root@photon [ ~ ]# mount -t cifs -o vers=3.0,credentials=/root/.linux@ad.bixnood.net //sofs.ad.bixnood.net/Linux /tmp/sofs.ad.bixnood.net/
mount error(22): Invalid argument
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
root@photon [ ~ ]# mount -t cifs -o vers=2.0,credentials=/root/.linux@ad.bixnood.net //sofs.ad.bixnood.net/Linux /tmp/sofs.ad.bixnood.net/
mount error(22): Invalid argument
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
root@photon [ ~ ]# mount -t cifs -o vers=1.0,credentials=/root/.linux@ad.bixnood.net //sofs.ad.bixnood.net/Linux /tmp/sofs.ad.bixnood.net/
mount error(13): Permission denied
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
root@photon [ ~ ]# uname -a
Linux photon 4.9.66-1.ph2-esx #1-photon SMP Thu Dec 7 01:41:22 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2660 v2 @ 2.20GHz GenuineIntel GNU/Linux
root@photon [ ~ ]# tdnf list installed | grep cifs-utils
cifs-utils.x86_64                           6.7-1.ph2                @System
```

**Comment by muhfugen** [comment] 2017-12-18 01:30
After playing with this some more it only seems to happen if `linux-esx` is installed. If it is removed on Photon 2.0, CIFS 2.0 works, but 1.0 and 3.0 are still broken when connecting to a SOFS cluster. Also if `linux-esx` is installed on Photon 1.0, CIFS 2.0 becomes broken, and 1.0 and 3.0 remain broken as they are with just `linux`.

**Comment by YustasSwamp** [comment] 2017-12-19 04:41
@muhfugen There are 2 major kernel types we have in Photon OS.
'linux-esx' - stripped down, optimized for ESXi
'linux' - generic kernel flavor with no support limits

To see what kernel will be used after next boot - check for /boot/photon.cfg symlink.
To see what kernel is currently loaded run `uname -r`

linux-esx has limited support of CIFS by design. It does not support for example SMB 2 & 3, Kerberos/SPNEGO advanced session setup, CIFS extended attributes (such as Posix extensions and ACLs)
Since your concern is SMB 2 & 3 let's exclude linux-esx from the picture.


Generic linux supports every CIFS/SMB feature except experimental SMB 3.1.1.
Out generic linux is pretty vanilla for CIFS, we didn't do any changes there.

Please check if you have non esx kernel running and try experiment (let's focus on Photon 2.0):

1. `uname -r` - should be nonzero
2. Enable cifs logging
`echo 7 >/proc/fs/cifs/cifsFYI`
`echo 1 >/proc/fs/cifs/traceSMB`
3. Run mount command which fails
4. put end of `dmesg` output (cifs related) here

Thanks!

**Comment by muhfugen** [comment] 2017-12-19 04:56
**CIFS 1.0 on linux**
```
root@build [ ~ ]# umount /mnt/sofs.ad.bixnood.net/Linux 
root@build [ ~ ]# uname -r
4.9.66-2.ph2
root@build [ ~ ]# echo 7 >/proc/fs/cifs/cifsFYI
root@build [ ~ ]# echo 1 >/proc/fs/cifs/traceSMB
root@build [ ~ ]# mount -t cifs -o credentials=/root/.linux@ad.bixnood.net //sofs.ad.bixnood.net/Linux /mnt/sofs.ad.bixnood.net/Linux/
mount error(13): Permission denied
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
root@build [ ~ ]# dmesg
[   91.215945] 0000 4e00 53ff 424d 0072 0000 0000 c801  ...N.SMBr.......
[   91.215948] 0000 0000 0000 0000 0000 0000 0000 01dd  ................
[   91.215950] 0000 0001 2b00 0200 4d4c 2e31 5832 3030  .....+..LM1.2X00
[   91.215952] 0032 4c02 4e41 414d 324e 312e 0200 544e  2..LANMAN2.1..NT
[   91.215954] 4c20 204d 2e30 3231 0200 4f50 4953 2058   LM 0.12..POSIX 
[   91.215956] 0032                                     2.
[   91.217308] 0000 cd00 53ff 424d 0072 0000 8000 c801  .....SMBr.......
[   91.217311] 0000 0000 0000 0000 0000 0000 0000 01dd  ................
[   91.217322] 0000 0001 0211 0300 0032 0001 4104 0000  ........2....A..
[   91.217324] 0000 0001 0000 0000 e3fc 8001 45f6 4f70  .............EpO
[   91.217334] 7885 01d3 0168 8800 be00 ff64 6dd5 597d  .x..h.....d..m}Y
[   91.217336] 8245 5db7 0129 0be1 608b 0676 2b06 0106  E..])....`v..+..
[   91.217338] 0505 a002 306c a06a 303c 063a 2b0a 0106  ....l0j.<0:..+..
[   91.217349] 0104 3782 0202 061e 2a09 4886 f782 0112  ...7.....*.H....
[   91.217351] 0202 0906 862a 8648 12f7 0201 0602 2a0a  ....*.H........*
[   91.217354] 4886 f786 0112 0202 0603 2b0a 0106 0104  .H.........+....
[   91.217356] 3782 0202 a30a 302a a028 1b26 6e24 746f  .7....*0(.&.$not
[   91.217357] 645f 6665 6e69 6465 695f 5f6e 4652 3443  _defined_in_RFC4
[   91.217359] 3731 4038 6c70 6165 6573 695f 6e67 726f  178@please_ignor
[   91.217361] 65                                               e
[   91.217372] 0000 cd00 53ff 424d 0072 0000 8000 c801  .....SMBr.......
[   91.217374] 0000 0000 0000 0000 0000 0000 0000 01dd  ................
[   91.217376] 0000 0001 0211 0300 0032 0001 4104 0000  ........2....A..
[   91.217378] 0000 0001 0000 0000 e3fc 8001 45f6 4f70  .............EpO
[   91.217380] 7885 01d3 0168 8800 be00 ff64 6dd5 597d  .x..h.....d..m}Y
[   91.217382] 8245 5db7 0129 0be1 608b 0676            E..])....`v.
[   91.217409] 0000 c600 53ff 424d 0073 0000 0000 c801  .....SMBs.......
[   91.217411] 0000 0000 0000 0000 0000 0000 0000 01dd  ................
[   91.217413] 0000 0002 ff0c 0000 5400 3240 0100 0000  .........T@2....
[   91.217415] 00 00 00 20 00 00 00 00 00 dc c0 00 80 8b 00     ... ...........
[   91.218180] 0000 9d01 53ff 424d 1673 0000 80c0 c801  .....SMBs.......
[   91.218182] 0000 0000 0000 0000 0000 0000 0000 01dd  ................
[   91.218184] 0803 0002 ff04 9d00 0001 e200 7200 4e01  .............r.N
[   91.218186] 4c54 534d 5053 0200 0000 0e00 0e00 3800  TLMSSP.........8
[   91.218188] 0000 0500 8902 69a2 c80c e884 a45b 0036  .......i....[.6.
[   91.218190] 0000 0000 0000 9c00 9c00 4600 0000 0a00  ...........F....
[   91.218192] 3900 0038 0000 420f 4900 5800 4e00 4f00  .98....B.I.X.N.O
[   91.218194] 4f00 4400 0200 0e00 4200 4900 5800 4e00  .O.D.....B.I.X.N
[   91.218196] 4f00 4f00 4400 0100 0a00 5300 4f00 4600  .O.O.D.....S.O.F
[   91.218198] 5300 3200 0400 1c00 6100 6400 2e00 6200  .S.2.....a.d...b
[   91.218200] 6900 7800 6e00 6f00 6f00 6400 2e00 6e00  .i.x.n.o.o.d...n
[   91.218202] 6500 7400 0300 2800 7300 6f00 6600 7300  .e.t...(.s.o.f.s
[   91.218204] 3200 2e00 6100 6400 2e00 6200 6900 7800  .2...a.d...b.i.x
[   91.218206] 6e00 6f00 6f00 6400 2e00 6e00 6500 7400  .n.o.o.d...n.e.t
[   91.218208] 0500 1c00 6100 6400 2e00 6200 6900 7800  .....a.d...b.i.x
[   91.218210] 6e00 6f00 6f00 6400 2e00 6e00 6500 7400  .n.o.o.d...n.e.t
[   91.218211] 0700 0800 f600 7045 854f d378 0001 0000  ......EpO.x.....
[   91.218217] 0000 0057 0069 006e 0064 006f 0077 0073  ..W.i.n.d.o.w.s.
[   91.218220] 0020 0053 0065 0072 0076 0065 0072 0020   .S.e.r.v.e.r. .
[   91.218222] 0032 0030 0031 0036 0020 0044 0061 0074  2.0.1.6. .D.a.t.
[   91.218223] 0061 0063 0065 006e 0074 0065 0072 0020  a.c.e.n.t.e.r. .
[   91.218225] 0031 0034 0033 0039 0033 0000 0057 0069  1.4.3.9.3...W.i.
[   91.218227] 006e 0064 006f 0077 0073 0020 0053 0065  n.d.o.w.s. .S.e.
[   91.218229] 0072 0076 0065 0072 0020 0032 0030 0031  r.v.e.r. .2.0.1.
[   91.218231] 0036 0020 0044 0061 0074 0061 0063 0065  6. .D.a.t.a.c.e.
[   91.218233] 006e 0074 0065 0072 0020 0036 002e 0033  n.t.e.r. .6...3.
[   91.218234] 00                                               .
[   91.218244] 0000 9d01 53ff 424d 1673 0000 80c0 c801  .....SMBs.......
[   91.218246] 0000 0000 0000 0000 0000 0000 0000 01dd  ................
[   91.218248] 0803 0002 ff04 9d00 0001 e200 7200 4e01  .............r.N
[   91.218250] 4c54 534d 5053 0200 0000 0e00 0e00 3800  TLMSSP.........8
[   91.218252] 0000 0500 8902 69a2 c80c e884 a45b 0036  .......i....[.6.
[   91.218254] 0000 0000 0000 9c00 9c00 4600            ...........F
[   91.218256] Status code returned 0xc0000016 NT_STATUS_MORE_PROCESSING_REQUIRED
[   91.218306] 0000 d801 53ff 424d 0073 0000 0000 c801  .....SMBs.......
[   91.218308] 0000 0000 0000 0000 0000 0000 0000 01dd  ................
[   91.218310] 0803 0003 ff0c 0000 5400 3240 0100 0000  .........T@2....
[   91.218312] 00 00 00 32 01 00 00 00 00 dc c0 00 80 9d 01     ...2...........
[   91.223538] 0000 bb00 53ff 424d 0073 0000 8000 c801  .....SMBs.......
[   91.223541] 0000 0000 0000 0000 0000 0000 0000 01dd  ................
[   91.223543] 0803 0003 ff04 bb00 0000 0000 9000 0000  ................
[   91.223545] 0057 0069 006e 0064 006f 0077 0073 0020  W.i.n.d.o.w.s. .
[   91.223547] 0053 0065 0072 0076 0065 0072 0020 0032  S.e.r.v.e.r. .2.
[   91.223549] 0030 0031 0036 0020 0044 0061 0074 0061  0.1.6. .D.a.t.a.
[   91.223551] 0063 0065 006e 0074 0065 0072 0020 0031  c.e.n.t.e.r. .1.
[   91.223553] 0034 0033 0039 0033 0000 0057 0069 006e  4.3.9.3...W.i.n.
[   91.223555] 0064 006f 0077 0073 0020 0053 0065 0072  d.o.w.s. .S.e.r.
[   91.223557] 0076 0065 0072 0020 0032 0030 0031 0036  v.e.r. .2.0.1.6.
[   91.223584] 0020 0044 0061 0074 0061 0063 0065 006e   .D.a.t.a.c.e.n.
[   91.223585] 74 00 65 00 72 00 20 00 36 00 2e 00 33 00 00     t.e.r. .6...3..
[   91.223598] 0000 bb00 53ff 424d 0073 0000 8000 c801  .....SMBs.......
[   91.223600] 0000 0000 0000 0000 0000 0000 0000 01dd  ................
[   91.223602] 0803 0003 ff04 bb00 0000 0000 9000 0000  ................
[   91.223604] 0057 0069 006e 0064 006f 0077 0073 0020  W.i.n.d.o.w.s. .
[   91.223606] 0053 0065 0072 0076 0065 0072 0020 0032  S.e.r.v.e.r. .2.
[   91.223608] 0030 0031 0036 0020 0044 0061            0.1.6. .D.a.
[   91.223632] 0000 6a00 53ff 424d 0075 0000 0000 c001  ...j.SMBu.......
[   91.223634] 0000 0000 0000 0000 0000 0000 0000 01dd  ................
[   91.223643] 0803 0004 ff04 0000 0800 0100 3f00 0000  .............?..
[   91.223645] 005c 005c 0073 006f 0066 0073 002e 0061  \.\.s.o.f.s...a.
[   91.223647] 0064 002e 0062 0069 0078 006e 006f 006f  d...b.i.x.n.o.o.
[   91.223649] 0064 002e 006e 0065 0074 005c 004c 0069  d...n.e.t.\.L.i.
[   91.223651] 006e 0075 0078 0000 3f3f 3f3f 003f       n.u.x...?????.
[   91.224026] 0000 2300 53ff 424d 2275 0000 80c0 c001  ...#.SMBu"......
[   91.224029] 0000 0000 0000 0000 0000 0000 0000 01dd  ................
[   91.224030] 03 08 04 00 00 00 00                             .......
[   91.224039] 0000 2300 53ff 424d 2275 0000 80c0 c001  ...#.SMBu"......
[   91.224041] 0000 0000 0000 0000 0000 0000 0000 01dd  ................
[   91.224043] 03 08 04 00 00 00 00                             .......
[   91.224045] Status code returned 0xc0000022 NT_STATUS_ACCESS_DENIED
[   91.224058] 0000 5400 53ff 424d 0075 0000 0000 c001  ...T.SMBu.......
[   91.224062] 0000 0000 0000 0000 0000 0000 0000 01dd  ................
[   91.224064] 0803 0005 ff04 0000 0800 0100 2900 0000  .............)..
[   91.224066] 005c 005c 0031 0030 002e 0031 002e 0031  \.\.1.0...1...1.
[   91.224068] 002e 0031 0038 005c 0049 0050 0043 0024  ..1.8.\.I.P.C.$.
[   91.224069] 0000 3f3f 3f3f 003f                      ..?????.
[   91.224714] 0000 3800 53ff 424d 0075 0000 8000 c001  ...8.SMBu.......
[   91.224716] 0000 0000 0000 0000 0000 0000 0803 01dd  ................
[   91.224725] 0803 0005 ff07 3800 0100 ff00 1fff ff00  .......8........
[   91.224727] 1fff 0700 4900 4350 0000 0000            .....IPC....
[   91.224738] 0000 3800 53ff 424d 0075 0000 8000 c001  ...8.SMBu.......
[   91.224740] 0000 0000 0000 0000 0000 0000 0803 01dd  ................
[   91.224742] 0803 0005 ff07 3800 0100 ff00 1fff ff00  .......8........
[   91.224743] 1fff 0700 4900 4350 0000 0000            .....IPC....
[   91.224756] 0000 7c00 53ff 424d 0032 0000 0000 c001  ...|.SMB2.......
[   91.224766] 0000 0000 0000 0000 0000 0000 0803 01dd  ................
[   91.224811] 0803 0006 380f 0000 0000 a000 000f 0000  .....8..........
[   91.224819] 0000 0000 0000 3800 4400 0000 0000 0100  .......8.D......
[   91.224821] 1000 3b00 0000 0000 0003 005c 0073 006f  ...;......\.s.o.
[   91.224823] 0066 0073 002e 0061 0064 002e 0062 0069  f.s...a.d...b.i.
[   91.224825] 0078 006e 006f 006f 0064 002e 006e 0065  x.n.o.o.d...n.e.
[   91.224827] 0074 005c 004c 0069 006e 0075 0078 0000  t.\.L.i.n.u.x...
[   91.225323] 0000 2300 53ff 424d 9c32 0001 80c0 c001  ...#.SMB2.......
[   91.225325] 0000 0000 0000 0000 0000 0000 0803 01dd  ................
[   91.225326] 03 08 06 00 00 00 00                             .......
[   91.225336] 0000 2300 53ff 424d 9c32 0001 80c0 c001  ...#.SMB2.......
[   91.225338] 0000 0000 0000 0000 0000 0000 0803 01dd  ................
[   91.225339] 03 08 06 00 00 00 00                             .......
[   91.225342] Status code returned 0xc000019c NT_STATUS_FS_DRIVER_REQUIRED
[   91.225348] 0000 2700 53ff 424d 0074 0000 0000 0001  ...'.SMBt.......
[   91.225350] 0000 0000 0000 0000 0000 0000 0000 01dd  ................
[   91.225351] 03 08 07 00 02 ff 00 00 00 00 00                 ...........
[   91.225485] 0000 2700 53ff 424d 0074 0000 8000 0001  ...'.SMBt.......
[   91.225487] 0000 0000 0000 0000 0000 0000 0000 01dd  ................
[   91.225488] 03 08 07 00 02 ff 00 27 00 00 00                 .......'...
[   91.225496] 0000 2700 53ff 424d 0074 0000 8000 0001  ...'.SMBt.......
[   91.225498] 0000 0000 0000 0000 0000 0000 0000 01dd  ................
[   91.225504] 03 08 07 00 02 ff 00 27 00 00 00                 .......'...
[   91.225609] CIFS VFS: cifs_mount failed w/return code = -13
```

**CIFS 3.0 on linux**
```
root@build [ ~ ]# mount -t cifs -o vers=3.0,credentials=/root/.linux@ad.bixnood.net //sofs.ad.bixnood.net/Linux /mnt/sofs.ad.bixnood.net/Linux/
mount error(5): Input/output error
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
root@build [ ~ ]# dmesg
[   98.425488] random: crng init done
[  103.756836] 0000 6600 53fe 424d 0040 0000 0000 0000  ...f.SMB@.......
[  103.756839] 0000 0002 0000 0000 0000 0000 0000 0000  ................
[  103.756841] 0000 0000 01e4 0000 0000 0000 0000 0000  ................
[  103.756843] 0000 0000 0000 0000 0000 0000 0000 0000  ................
[  103.756845] 0000 0000 0024 0001 0001 0000 0057 0000  ....$.......W...
[  103.756847] 00f1 79d0 6931 6344 768a bb21 503d e9ea  ...y1iDc.v!.=P..
[  103.756849] 0000 0000 0000 0000 0300                 ..........
[  103.757488] 0000 f800 53fe 424d 0040 0000 0000 0000  .....SMB@.......
[  103.757491] 0000 0001 0001 0000 0000 0000 0000 0000  ................
[  103.757493] 0000 0000 01e4 0000 0000 0000 0000 0000  ................
[  103.757494] 0000 0000 0000 0000 0000 0000 0000 0000  ................
[  103.757496] 0000 0000 0041 0001 0300 0000 64be d5ff  ....A........d..
[  103.757498] 7d6d 4559 b782 295d e101 8b0b 0057 0000  m}YE..])....W...
[  103.757509] 0000 0080 0000 0080 0000 0080 c746 56ea  ............F..V
[  103.757511] 7885 01d3 5007 e2c9 5e73 01d3 0080 0078  .x...P..s^....x.
[  103.757513] 0000 0000 7660 0606 062b 0501 0205 6ca0  ....`v..+......l
[  103.757519] 6a30 3ca0 3a30 0a06 062b 0401 8201 0237  0j.<0:..+.....7.
[  103.757521] 1e02 0906 862a 8248 12f7 0201 0602 2a09  ....*.H........*
[  103.757523] 4886 f786 0112 0202 0a06 862a 8648 12f7  .H........*.H...
[  103.757525] 0201 0302 0a06 062b 0401 8201 0237 0a02  ......+.....7...
[  103.757527] 2aa3 2830 26a0 241b 6f6e 5f74 6564 6966  .*0(.&.$not_defi
[  103.757529] 656e 5f64 6e69 525f 4346 3134 3837 7040  ned_in_RFC4178@p
[  103.757531] 656c 7361 5f65 6769 6f6e 6572            lease_ignore
[  103.757547] 0000 f800 53fe 424d 0040 0000 0000 0000  .....SMB@.......
[  103.757549] 0000 0001 0001 0000 0000 0000 0000 0000  ................
[  103.757551] 0000 0000 01e4 0000 0000 0000 0000 0000  ................
[  103.757553] 0000 0000 0000 0000 0000 0000 0000 0000  ................
[  103.757555] 0000 0000 0041 0001 0300 0000 64be d5ff  ....A........d..
[  103.757570] 0000 7800 53fe 424d 0040 0000 0000 0000  ...x.SMB@.......
[  103.757572] 0001 0003 0000 0000 0000 0000 0001 0000  ................
[  103.757574] 0000 0000 01e4 0000 0000 0000 0000 0000  ................
[  103.757576] 0000 0000 0000 0000 0000 0000 0000 0000  ................
[  103.757578] 0000 0000 0019 0100 0000 0000 0000 0000  ................
[  103.757580] 0058 0020 0000 0000 0000 0000            X. .........
[  103.757932] 0000 2a01 53fe 424d 0040 0000 0016 c000  ...*.SMB@.......
[  103.757934] 0001 0001 0001 0000 0000 0000 0001 0000  ................
[  103.757936] 0000 0000 01e4 0000 0000 0000 0581 5c00  ...............\
[  103.757938] 3c70 0008 0000 0000 0000 0000 0000 0000  p<..............
[  103.757940] 0000 0000 0009 0000 0048 00e2 544e 4d4c  ........H...NTLM
[  103.757942] 5353 0050 0002 0000 000e 000e 0038 0000  SSP.........8...
[  103.757944] 0205 a289 2839 0662 fdef b938 0000 0000  ....9(b...8.....
[  103.757946] 0000 0000 009c 009c 0046 0000 000a 3839  ........F.....98
[  103.757948] 0000 0f00 0042 0049 0058 004e 004f 004f  ....B.I.X.N.O.O.
[  103.757949] 0044 0002 000e 0042 0049 0058 004e 004f  D.....B.I.X.N.O.
[  103.757951] 004f 0044 0001 000a 0053 004f 0046 0053  O.D.....S.O.F.S.
[  103.757953] 0032 0004 001c 0061 0064 002e 0062 0069  2.....a.d...b.i.
[  103.757955] 0078 006e 006f 006f 0064 002e 006e 0065  x.n.o.o.d...n.e.
[  103.757957] 0074 0003 0028 0073 006f 0066 0073 0032  t...(.s.o.f.s.2.
[  103.757959] 002e 0061 0064 002e 0062 0069 0078 006e  ..a.d...b.i.x.n.
[  103.757961] 006f 006f 0064 002e 006e 0065 0074 0005  o.o.d...n.e.t...
[  103.757963] 001c 0061 0064 002e 0062 0069 0078 006e  ..a.d...b.i.x.n.
[  103.757964] 006f 006f 0064 002e 006e 0065 0074 0007  o.o.d...n.e.t...
[  103.757966] 0008 c746 56ea 7885 01d3 0000 0000       ..F..V.x......
[  103.757975] 0000 2a01 53fe 424d 0040 0000 0016 c000  ...*.SMB@.......
[  103.757977] 0001 0001 0001 0000 0000 0000 0001 0000  ................
[  103.757979] 0000 0000 01e4 0000 0000 0000 0581 5c00  ...............\
[  103.757981] 3c70 0008 0000 0000 0000 0000 0000 0000  p<..............
[  103.757982] 0000 0000 0009 0000 0048 00e2 544e 4d4c  ........H...NTLM
[  103.757985] Status code returned 0xc0000016 STATUS_MORE_PROCESSING_REQUIRED
[  103.758035] 0000 8a01 53fe 424d 0040 0000 0000 0000  .....SMB@.......
[  103.758037] 0001 0003 0000 0000 0000 0000 0002 0000  ................
[  103.758039] 0000 0000 01e4 0000 0000 0000 0581 5c00  ...............\
[  103.758041] 3c70 0008 0000 0000 0000 0000 0000 0000  p<..............
[  103.758043] 0000 0000 0019 0100 0000 0000 0000 0000  ................
[  103.758045] 0058 0132 0000 0000 0000 0000            X.2.........
[  103.760460] 0000 4800 53fe 424d 0040 0000 0000 0000  ...H.SMB@.......
[  103.760463] 0001 0003 0009 0000 0000 0000 0002 0000  ................
[  103.760464] 0000 0000 01e4 0000 0000 0000 0581 5c00  ...............\
[  103.760466] 3c70 0008 5f0c f870 c796 3137 d696 fef2  p<..._p...71....
[  103.760468] 862d 6438 0009 0000 0048 0000            -.8d....H...
[  103.760482] 0000 4800 53fe 424d 0040 0000 0000 0000  ...H.SMB@.......
[  103.760484] 0001 0003 0009 0000 0000 0000 0002 0000  ................
[  103.760486] 0000 0000 01e4 0000 0000 0000 0581 5c00  ...............\
[  103.760488] 3c70 0008 5f0c f870 c796 3137 d696 fef2  p<..._p...71....
[  103.760489] 862d 6438 0009 0000                      -.8d....
[  103.760496] 0000 8000 53fe 424d 0040 0001 0000 0000  .....SMB@.......
[  103.760498] 0003 0002 0000 0000 0000 0000 0003 0000  ................
[  103.760500] 0000 0000 01e4 0000 0000 0000 0581 5c00  ...............\
[  103.760502] 3c70 0008 0000 0000 0000 0000 0000 0000  p<..............
[  103.760504] 0000 0000 0009 0000 0048 0036            ........H.6.
[  103.760730] 0000 5000 53fe 424d 0040 0001 0000 0000  ...P.SMB@.......
[  103.760732] 0003 0002 0001 0000 0000 0000 0003 0000  ................
[  103.760734] 0000 0000 01e4 0000 0001 0000 0581 5c00  ...............\
[  103.760736] 3c70 0008 0000 0000 0000 0000 0000 0000  p<..............
[  103.760738] 0000 0000 0010 0001 0830 0000 0070 0000  ........0...p...
[  103.760740] 00a9 0012                                ....
[  103.760748] 0000 5000 53fe 424d 0040 0001 0000 0000  ...P.SMB@.......
[  103.760749] 0003 0002 0001 0000 0000 0000 0003 0000  ................
[  103.760751] 0000 0000 01e4 0000 0001 0000 0581 5c00  ...............\
[  103.760753] 3c70 0008 0000 0000 0000 0000 0000 0000  p<..............
[  103.760755] 0000 0000 0010 0001 0830 0000 0070 0000  ........0...p...
[  103.760763] 0000 9200 53fe 424d 0040 0001 0000 0000  .....SMB@.......
[  103.760765] 000b 0002 0000 0000 0000 0000 0004 0000  ................
[  103.760768] 0000 0000 01e4 0000 0001 0000 0581 5c00  ...............\
[  103.760794] 3c70 0008 0000 0000 0000 0000 0000 0000  p<..............
[  103.760796] 0000 0000 0039 0000 0204 0014 ffff ffff  ....9...........
[  103.760798] ffff ffff ffff ffff ffff ffff 0078 0000  ............x...
[  103.760800] 001a 0000 0000 0000 0000 0000 0000 0000  ................
[  103.760801] 4000 0000 0001 0000 0000 0000            .@..........
[  103.761617] CIFS VFS: validate protocol negotiate failed: -11
[  103.762389] CIFS VFS: cifs_mount failed w/return code = -5
root@build [ ~ ]# 

```

**Comment by muhfugen** [comment] 2017-12-19 05:06
Also just a FYI, but regarding not supporting CIFS 2 or 3 in `linux-esx`, in Windows Server build 1709, CIFS 1 is disabled by default. Although this isnt relevant to this issue as the SOFS cluster is running build 1607, I just thought i'd let you know as i'm sure more people might start submitting bug reports in the future about not being able to connect to Windows shares since `linux-esx` is now the default kernel in Photon 2.

**Comment by srivatsabhat** [comment] 2018-01-04 04:46
@muhfugen, thank you for your detailed bug report and testing efforts!

The SMB3 mount regression was caused by this commit in linux mainline:

commit 0603c96f3af50 "SMB: Validate negotiate (to protect against downgrade) even if signing off"

It was later fixed in upstream by a subsequent commit:

commit 4587eee04e2ac "SMB3: Validate negotiate request must always be signed"

However, backporting this patch to the stable kernels used by Photon OS (4.4 or 4.9) unfortunately doesn't fix the problem; it appears that a more involved patch is required. I have reported the details and my attempted fix to the SMB developers on the linux-kernel mailing list:
https://lkml.org/lkml/2018/1/3/892

So in the meantime, I have added patches to Photon OS 1.0 and 2.0 to fix the regression by reverting the original commit that broke SMB3 mounting. They are being tested at the moment, and will be pushed out soon.

**Comment by srivatsabhat** [comment] 2018-01-08 21:31
@muhfugen, We have updated Photon OS 1.0 and 2.0 kernels to fix the mount regression. Could you please give them a try and let us know if they work for you?

The kernel versions that include the fix are: 4.4.110-1 (or higher) in Photon OS 1.0 and 4.9.75-1 (or higher) in Photon OS 2.0. To get these updated kernels, just run `tdnf upgrade linux` and reboot.

Thank you!

**Comment by muhfugen** [comment] 2018-01-09 02:56
@srivatsabhat I can confirm that the latest update for the linux kernel on both Photon 1 and 2 has fixed the issue of not being able to connect to a SOFS cluster with SMB 3. Thanks a lot!

**Comment by srivatsabhat** [comment] 2018-01-09 21:45
@muhfugen, I'm glad to hear that! Thanks a lot for reporting the bug and testing the fix!

**Closed** 2018-01-11 14:11 UTC
