### ISSUE TITLE
Bash executing a command causes signal 17 - child died 

### ISSUE THREAD

**Issue by Daniel-Nashed** [vmware/photon#1189] opened 2021-04-30 08:29 UTC
Below is the simplified example script.
It works well on all other Linux environments I tested and raises signal 17 on Photon OS 4.0 (I did not test any other version).

Whatever command I call I get signal 17. So this is just a basic example to reproduce.

Is this a known issue? Is there any work-around? 
For now I am avoiding to trap signal 17 when running on Photon OS

Thanks

Daniel

```
#!/bin/bash
stop_server()
{
  echo "signal catched"
}

trap "stop_server" 17

echo "wait first 5 seconds"
sleep 5
SERVER_SETUP=$(echo test)
echo "SERVER_SETUP: [$SERVER_SETUP]"
sleep 5
echo done
```

**Comment by YustasSwamp** [comment] 2021-04-30 08:38
Interesting!! Thanks for report and nice repro. Will take a look.

**Comment by Daniel-Nashed** [comment] 2021-04-30 09:22
that's for you quick reply!  If you want me anything to test, let me know any time.

**Comment by ssahani** [comment] 2021-04-30 12:44
I tried to reproduce it 

```
> ./a.sh
wait first 5 seconds
signal catched
signal catched
SERVER_SETUP: [test]
signal catched
```

```
sus@Ares [ ~/tmp ]$ rpm -qi bash
Name        : bash
Version     : 5.0
Release     : 2.ph4
Architecture: x86_64
Install Date: Thu 25 Feb 2021 02:09:54 PM UTC
Group       : System Environment/Base
Size        : 1911698
License     : GPLv3
Signature   : RSA/SHA1, Thu 25 Feb 2021 06:24:25 AM UTC, Key ID c0b5e0ab66fd4949
Source RPM  : bash-5.0-2.ph4.src.rpm
Build Date  : Wed 24 Feb 2021 09:53:23 PM UTC
Build Host  : photon-616a4c2
Vendor      : VMware, Inc.
URL         : http://www.gnu.org/software/bash/
Summary     : Bourne-Again SHell
Description :
The package contains the Bourne-Again SHell
sus@Ares [ ~/tmp ]$ cat /etc/os-release
NAME="VMware Photon OS"
VERSION="4.0"
ID=photon
VERSION_ID=4.0
PRETTY_NAME="VMware Photon OS/Linux"
ANSI_COLOR="1;34"
HOME_URL="https://vmware.github.io/photon/"
BUG_REPORT_URL="https://github.com/vmware/photon/issues"
```

```
sus@Ares [ ~/tmp ]$ cat a.sh
#!/bin/bash
stop_server()
{
  echo "signal catched"
}

trap "stop_server" 17

echo "wait first 5 seconds"
sleep 5
SERVER_SETUP=$(echo test)
echo "SERVER_SETUP: [$SERVER_SETUP]"
sleep 5
```

```

**Comment by dcasota** [comment] 2021-04-30 18:54
Right after @YustasSwamp published his comment, I was able to reproduce a not known effect - after running the demo script, each additional console command or rerun of the script "trapped" like it were a temporary parallel command fork.  Unfortunately I didn't take a screen shot...

Right now, fresh ph4 installation from identical image, no updates, logged-in as root or non-root, it isn't reproducible anymore. 
Does the trap command have a timestamp event dependency with a very rare fork-similar side effect ?? Sorry guys, I'm a Linux beginner, and learning on Photon OS everything I can find :)

**Comment by ppadmavilasom** [comment] 2021-04-30 19:44
fyi - same behavior (as noted above by op) on alpine 3.13.3 with bash 5.1.0

**Comment by Daniel-Nashed** [comment] 2021-05-03 08:10
Checked all my environments.  And I can reproduce on openSUSE Tumbleweed.  
That's the only 5.x bash I have.  
It looked like a bug or changed behavior in 5.x.   
I would say it is a bug, because the sub process should be properly terminated.  
Not sure what causes the signal to be generated.  

```
rpm -qi bash
Name        : bash
Version     : 5.1.4
Release     : 1.4
Architecture: x86_64
Install Date: Mon May  3 09:26:47 2021
Group       : System/Shells
Size        : 1349761
License     : GPL-3.0-or-later
Signature   : RSA/SHA256, Thu Mar 25 21:15:42 2021, Key ID b88b2fd43dbdc284
Source RPM  : bash-5.1.4-1.4.src.rpm
Build Date  : Thu Mar 25 21:11:18 2021
Build Host  : lamb59
Packager    : https://bugs.opensuse.org
Vendor      : openSUSE
URL         : http://www.gnu.org/software/bash/bash.html
Summary     : The GNU Bourne-Again Shell
```

**Comment by Daniel-Nashed** [comment] 2021-05-04 07:46
If this is really a bash problem, where would I need to report it?
Or can the Photon OS report an issue upstream?

**Comment by dcasota** [comment] 2021-05-04 08:36
The default behavior with resulting 'command not found' on interactive shell + pre-executed trap "regress" 17 + same trap inside the script isn't nice. It happpens on Ph2 (Bash 4.4.18)+Ph4 (latest). You've already suggested to disable the trap temporarily. 

A trap method to catch issues must work in an environment of a shell script that runs a service, and interactively. The bash [maintainer news](https://tiswww.case.edu/php/chet/bash/NEWS) lists somewhat of new features which might have impact.

That said, the simplified example script provided won't get your issue of the shell script (including the function mentioned of  ```tail -f```) that runs a [service](https://vmware.github.io/photon/docs/administration-guide/managing-services-withsystemd/) on Photon.

Unfortunately no code upstream here. But, hope this helps. Daniel C.

**Comment by Daniel-Nashed** [comment] 2021-05-04 20:00
thanks for the link! there are a couple of changes in bash 5.0 around signal handling.  
what is kind of odd is that we get a ``SIGCHLD`` at all when invoking commands.  
Other applications I work with see SIGCHLD as a abnormal process termination, which tells the application the invoked process crashed.  
I tried to run simple commands and they all trigger the signal.
If this is the new intended behavior, I will just remove signal 17 completely from my scripts.
It's there to ensure background threads reading from console terminate properly when a shell is closed.

1. start tail -f /mylog.file & 
2. trap for termination 
3. read from the console

we had issues earlier that when the shell was closed, the shell continued to read from a dead pipe.
that's why I added paranoid signal catching .. 

If someone has ideas to improve  the error handling .. any suggestion is welcome..

here is the code --> https://github.com/IBM/domino-docker/blob/6f1ce7841612765fb2c63540980e1b6facea545c/start_script/rc_domino_script#L1436


and this might be the change 

```
w. Bash removes SIGCHLD from the set of blocked signals if it's blocked at shell
   startup.
```

**Comment by YustasSwamp** [comment] 2021-05-24 22:54
This is not a bug, but change in 5.0 which gives you more control.

From release notes: https://lists.gnu.org/archive/html/bug-bash/2019-01/msg00063.html

```
+========== NEWS ==========+
This is a terse description of the new features added to bash-5.0 since
the release of bash-4.4.  As always, the manual page (doc/bash.1) is
the place to look for complete descriptions.

...

n. The SIGCHLD trap is run once for each exiting child process even if job
   control is not enabled when the shell is in Posix mode.
```

This is the change
https://git.savannah.gnu.org/cgit/bash.git/commit/?id=d233b485e83c3a784b803fb894280773f16f2deb

 ```
@@ -3640,7 +3729,7 @@ itrace("waitchld: waitpid returns %d block = %d children_exited = %d", pid, bloc
     }
 
   /* Call a SIGCHLD trap handler for each child that exits, if one is set. */
-  if (job_control && children_exited &&
+  if (children_exited &&
       (signal_is_trapped (SIGCHLD) || trap_list[SIGCHLD] == (char *)IMPOSSIBLE_TRAP_HANDLER) &&
       trap_list[SIGCHLD] != (char *)IGNORE_SIG)
     {
```
 
And looks like this code existed even in older version of bash and get triggered then `job_control` is enabled.

@Daniel-Nashed Adding `set -m` in the beginning of your script will reproduce the issue in older bash (before 5.0)

Closing it as not a bug / won't fix.

**Closed by YustasSwamp** 2021-05-24 22:54 UTC
Labels: 4.0, bug, package

**Comment by Daniel-Nashed** [comment] 2021-05-25 21:55
Thanks! This confirms what I thought after the last comments. 
That's for the very useful links! this is helpful to understand the background.
So I will change the code on our end to remove the signal for all platforms.
