### ISSUE TITLE
NTP 4.2.8p14-2 Uninstallable

### ISSUE THREAD

**Issue by paddatrapper** [vmware/photon#1090] opened 2021-01-05 14:15 UTC
It appears libseccomp is currently uninstallable:

```
$ tdnf install -y kubelet=1.18.0-0 kubeadm=1.18.0-0 kubectl=1.18.0-0 socat ebtables ntp libseccomp nfs-utils
[...]
Installing/Updating: libseccomp-2.4.0-2.ph3.x86_64
Error(1469) : Unknown error
```

We are encountering this in our CI pipeline, so full logs are available here: https://app.circleci.com/pipelines/github/flanksource/konfigadm/608/workflows/f455b354-96fb-46c6-9863-7add919e9a79/jobs/2446/tests

**Comment by suezzelur** [comment] 2021-01-05 23:10
Assuming you are using the google cloud repo, I am not able to repro this:
```
root [ / ]# cat <<EOF > /etc/yum.repos.d/kubernetes.repo
> [kubernetes]
> name=Kubernetes
> baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
> enabled=1
> gpgcheck=1
> repo_gpgcheck=1
> gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
> EOF
root [ / ]# tdnf install -qy kubelet=1.18.0-0 kubeadm=1.18.0-0 kubectl=1.18.0-0 socat ebtables ntp libseccomp nfs-utils
importing key from https://packages.cloud.google.com/yum/doc/yum-key.gpg
Error verifying signature of: /var/cache/tdnf/kubernetes/rpms/Packages/db7cb5cb0b3f6875f54d10f02e625573988e3e91fd4fc5eef0b1876bb18604ad-kubernetes-cni-0.8.7-0.x86_64.rpm
importing key from https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
using empty dict to provide pw_dict
chown root:sys /var/lib/rpcbind
```

**Comment by oliverkurth** [comment] 2021-01-06 01:41
I am not able to reproduce this either. We need more information:
- what version of tdnf is used? Use `tdnf --version`
- the kubernetes repo file
- what happened before the tdnf install command?
- what is the photon container id?

Ideally, with the same container id and a script we should be able to reproduce this.

The error code`1469` is the same as `ERROR_TDNF_RPM_BASE - 1`. Very suspicious.

If I interpret the log correctly, `libseccomp` was installed despite the error. Weird.

**Comment by paddatrapper** [comment] 2021-01-06 08:47
> what version of tdnf is used? Use tdnf --version

```
tdnf: 2.1.1
```

> the kubernetes repo file

```
[kubernetes]
name=kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1

gpgcheck=0
```

> what is the photon container id?

[tarun18/photon:3.0](https://hub.docker.com/layers/tarun18/photon/3.0/images/sha256-a093e59ec743ff8b649055230de42ca57a25c8aea6ebde0e413cf24fb0bb15e5?context=explore)

I can replicate in a clean docker image. It is NTP that fails to install, not libseccomp. It also seems to work on the official photon images, but not the image we are using. The reason we're not using the official images is because we need systemd support (for docker-in-docker testing). The Dockerfile can be found here: https://github.com/flanksource/footloose/pull/3/commits/58ed015deef2a54097f394807bce908cda2e4403. It is a fairly old build and I'm going to try get it rebuilt properly soon.

```
$ docker run -it --rm tarun18/photon:3.0 bash
root [ / ]# tdnf install -y ntp
Refreshing metadata for: 'VMware Photon Extras 3.0 (x86_64)'
Refreshing metadata for: 'VMware Photon Linux 3.0 (x86_64) Updates'
Refreshing metadata for: 'VMware Photon Linux 3.0 (x86_64)'
photon                                 2498249   100%
Installing:
ntp                          x86_64         4.2.8p14-2.ph3      photon-updates   6.44M 6756169

Total installed size:   6.44M 6756169

Downloading:
ntp                                    3693850   100%
Testing transaction
Running transaction
You are required to change your password immediately (password expired)
groupadd: PAM: Authentication token is no longer valid; new one required
useradd: group 'ntp' does not exist
Error(1469) : Unknown error
```

**Comment by ssahani** [comment] 2021-01-06 14:51
```

You are required to change your password immediately (password expired)
groupadd: PAM: Authentication token is no longer valid; new one required

```

```
sudo chage -l root 
```
and
```
$ sudo passwd root
```

**Comment by oliverkurth** [comment] 2021-01-06 18:34
Thanks @paddatrapper , I can reproduce it now. And using @ssahani 's advice, when I do `passwd root` before installing ntp it works. I tried updating tdnf to the latest available in our repos (2.1.2-3), issue still happens.

I will now try to find the root cause.

**Comment by oliverkurth** [comment] 2021-01-06 20:15
Got it: there is a legit error in the container - the password for root is expired. Therefore the command `groupadd` in the preinstall script in `ntp` fails, and the user `ntp` cannot be added. `tdnf` unfortunately did not interpret the error return from `rpmtsRun()` correctly, and bails with `1469`. This was fixed recently with https://github.com/vmware/tdnf/pull/203 , and the error now would be a little more descriptive:

```
...
ntp                                    3693850   100%
Testing transaction
Running transaction
You are required to change your password immediately (password expired)
groupadd: PAM: Authentication token is no longer valid; new one required
useradd: group 'ntp' does not exist
Error(1525) : rpm transaction failed
```

The error is legit from tdnf perspective, rpm install failed. It failed because the root password expired. However that does not make much sense in a container, so this should really be fixed in `/etc/login.defs` by setting `PASS_MAX_DAYS` to `-1` (never expire). Setting it has no immediate effect however.

As a temporary workaround, just do:
```
passwd -x -1 root
```
before installing any packages. Long term I think this should be fixed by unsetting the expiry duration in `/etc/shadow` for container builds, from:
```
# cat /etc/shadow|grep root
root:x:18504:0:90:7:::
```
to
```
root [ /build/build ]# cat /etc/shadow|grep root
root:x:18504:0::7:::
```

**Comment by paddatrapper** [comment] 2021-01-07 09:33
Thanks for the workaround and diagnosis!

**Closed** 2021-02-28 09:14 UTC
Labels: docker
