### ISSUE TITLE
Failed to run tdnf distro-sync in vmware/photon:1.0

### ISSUE THREAD

**Issue by reasonerjt** [vmware/photon#700] opened 2017-10-25 09:01 UTC
My Dockerfile looks like this:

```
FROM vmware/photon:1.0
RUN tdnf erase vim -y     && tdnf distro-sync -y --rpmverbosity debug    && tdnf clean all
```

Some relevant error messages of `docker build`:
```
......
error: ^[[0m^[[91munpacking of archive failed on file /sys: cpio: chmod failed - Read-only file system
error: filesystem-1.1-2.ph1.x86_64: install failed
^[[0m^[[91mD: ========== +++ glibc-2.22-14.ph1 x86_64-linux 0x2
......
Testing transaction
Running transaction
Error(-1) : Unknown error -1601
The command '/bin/sh -c tdnf erase vim -y     && tdnf distro-sync -y --rpmverbosity debug    && tdnf clean all' returned a non-zero code: 255
```

Also attaching the complete output:

[output.txt](https://github.com/vmware/photon/files/1413931/output.txt)

This looks like a regression of #624

**Comment by ppadmavilasom** [comment] 2017-10-25 17:27
@reasonerjt this is due to the base docker image not updated with latest filesystem update. will fix and update.

**Comment by robertqi** [comment] 2017-10-25 20:25
Now the issue is gone, we pushed fix there. Please use vmware/photon:1.0 now. Thanks.

**Closed** 2017-11-01 00:50 UTC
