### ISSUE TITLE
[Pi3b issues] Failed to resolve group docker: No such process & SSH doesn't work & password expires after every reboot

### ISSUE THREAD

**Issue by C-Fu** [vmware/photon#965] opened 2020-01-08 14:23 UTC
Commands used after fresh boot:

```
#tdnf upgrade
#tdnf update
#tdnf list | grep docker
#tdnf install docker
#systemctl start docker
> A dependency job for docker.service failed. See journalctl -xe for details.
#journalctl -xe | grep docker
> Failed to resolve group docker: No such process
#tdnf install docker*
#systemctl start docker
> A dependency job for docker.service failed. See journalctl -xe for details.
```

I figured since the documentation jumped from installing on RPi3B to Deploying a Containerized Application in Photon OS (with docker) then docker would've been preinstalled. Nope. That's fine. Go ahead and install docker. Docker group wasn't automatically created. 

```
# groupadd docker
# usermod -aG docker $USER
# systemctl enable docker
# systemctl start docker
```

Everything works. Suggestion: Add the 2 lines to create the docker group during install, somehow? My linux-fu isn't strong enough.

Also, SSH to my machine straight after changing password doesn't work. Using "changeme" also doesn't work.

Edit: Seems like changing the password to xxxx > reboot > change the password again to changeme > reboot > change the password again to xxxx works.

**Comment by YustasSwamp** [comment] 2020-02-20 17:37
docker group should be added as part of docker installation:
https://github.com/vmware/photon/blob/3.0/SPECS/docker/docker-18.06.spec#L181

Can you provide an output of `tdnf install docker`, please?

**Comment by YustasSwamp** [comment] 2020-02-21 20:06
`Edit: Seems like changing the password to xxxx > reboot > change the password again to changeme > reboot > change the password again to xxxx works.`

Seems like you do force reboot without syncing filesystem
How do you reboot the RPi3?

**Comment by YustasSwamp** [comment] 2020-08-12 21:13
Unable to reproduce this. Closing as not enough info.

**Closed by YustasSwamp** 2020-08-12 21:13 UTC
