### ISSUE TITLE
Issues with perl and find command  failing on  photon OS

### ISSUE THREAD

**Issue by reachrkr** [vmware/photon#681] opened 2017-08-23 10:32 UTC
Installed latest version of photon  OS 
https://bintray.com/vmware/photon/download_file?file_path=photon-custom-hw11-1.0-62c543d.ova

1) Perl throws a locale warning issues, 

`root@photon-machine [ ~ ]# perl -v
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").

This is perl 5, version 22, subversion 1 (v5.22.1) built for x86_64-linux-thread-multi

Copyright 1987-2015, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.
`

2) Did a search of file "Safe.pm"  

it lists the file only under /usr/lib/perl5/5.22.1/Safe.pm

Its unable to list the same file in /usr/local/lib64/perl5/5.22.1/

`root@photon-machine [ ~ ]# find / -name "Safe.pm"
/usr/lib/perl5/5.22.1/Safe.pm
root@photon-machine [ ~ ]# ls  /usr/local/lib64/perl5/5.22.1/Safe.pm
/usr/local/lib64/perl5/5.22.1/Safe.pm
`

**Comment by YustasSwamp** [comment] 2017-09-07 09:32
Thanks to reaching us.

1. It is known issue of Photon OS 1.0 (Fixed in 2.0). en_US.UTF-8 set but not installed.
steps to fix:
# touch /usr/share/locale/locale.alias
# locale-gen.sh

2. Not a bug.
/usr/local/lib64 is a symlink to /usr/lib.
`find` does not follow symlinks by default

**Closed by YustasSwamp** 2017-09-07 09:32 UTC
