### ISSUE TITLE
Prebuilt OVF distribution configuration blocks guest operations

### ISSUE THREAD

**Issue by alexp789** [vmware/photon#572] opened 2016-12-01 14:34 UTC
**Problem**
When deploying the prebuilt OVF distribution (for example https://bintray.com/vmware/photon/download_file?file_path=photon-custom-hw10-1.0-13c08b6.ova) the default configuration won't allow the use of guest operations to inject cloud-init directly into `/var/lib/cloud/seed/nocloud/` within the container without manual intervention.

**Cause**
The root cause of this issue is the use of `chage -d 0 root` in support/cloud-image-builder/ova/ova-custom-patch.sh

    #!/bin/bash
    echo -e "changeme\nchangeme" | passwd root
    chage -d 0 root

This breaks the guest authentication which guestOperationsManager.processManager relies on until a root password has been configured.

**Possible Solutions**

- Allow an optional credential to be specified in the OVF environment, this would allow a password to be set which would then allow guestOperations to succeed.
- Remove the forced password change requirement. (not really viable)

**Why is this necessary**
There are a number of scenarios where it will be preferred for Photon OS to be deployed directly from an OVF (which means vSphere Guest Customisation isn't possible) and no DHCP infrastructure is available to support cloud-init over the network.  Being able to automate the end-to-end configuration of Photon OS in these environments using only standard vSphere API's is highly desirable.

Thanks

Alex

**Comment by alexp789** [comment] 2016-12-01 14:37
I have just noticed that implementing #549 would remove the need for this.

**Comment by sharathjg** [comment] 2016-12-06 20:42
dupe of #549

**Closed by sharathjg** 2016-12-06 20:42 UTC
