### ISSUE TITLE
VMware Guestinfo interface for PhotonOS

### ISSUE THREAD

**Issue by jm66** [vmware/photon#549] opened 2016-10-27 01:37 UTC
Wondering if possible to implement in PhotonOS the VMware Guestinfo interface as [CoreOS](https://coreos.com/os/docs/latest/booting-on-vmware.html#cloud-config) does for provisioning cloud-init user_data and other [config props](https://github.com/coreos/coreos-cloudinit/blob/master/Documentation/vmware-guestinfo.md). I found it really useful and looks better integrated to VMware.

```
guestinfo.hostname = "photon"
guestinfo.interface.0.role = "private"
guestinfo.dns.server.0 = "8.8.8.8"
guestinfo.interface.0.route.0.gateway = "192.168.178.1"
guestinfo.interface.0.route.0.destination = "0.0.0.0/0"
guestinfo.interface.0.mac = "00:0c:29:63:92:5c"
guestinfo.interface.0.name = "eno1*"
guestinfo.interface.0.dhcp = "no"
guestinfo.interface.0.ip.0.address = "192.168.178.97/24"
```

More info [here](https://github.com/coreos/coreos-cloudinit/tree/master/datasource/vmware).

Thanks
JM

**Comment by alanrenouf** [comment] 2016-11-04 16:02
I would also love this!

**Comment by alanrenouf** [comment] 2016-11-04 16:03
Make sure it has a password entry as well so we can set the password on first boot ;)

**Comment by rgeorgiev** [comment] 2016-12-08 22:36
Any progress on this request?

**Comment by jm66** [comment] 2017-01-27 15:16
Not sure why tagged as "Nice to have".

**Comment by rgeorgiev** [comment] 2017-02-19 12:23
If you don't plan to implement it, then close the issue.
But please give some update, in some form.

**Comment by kaushik229** [comment] 2017-02-21 18:47
If feasible, we target this to be available for next release of photon.
Will update accordingly.

**Comment by ppadmavilasom** [comment] 2017-04-10 21:52
@kaushik229 any updates on this?

**Comment by kaushik229** [comment] 2017-04-19 17:20
The changes are in test. Will update once done. Anish is handling it.

**Comment by fjudith** [comment] 2017-07-07 18:19
any update ?

**Comment by kaushik229** [comment] 2017-07-07 20:39
I think this is already implemented by Anish.

@suezzelur 
 Can you please comment on this ?

Thanks,
Kaushik

**Comment by suezzelur** [comment] 2017-07-08 00:35
Yes, the required changes are in our master branch.

**Comment by charandas** [comment] 2017-12-18 22:02
If the required changes are in, can you @suezzelur please share which ovfEnv properties does the code look at?

I have a Photon 2.0 OVA from maybe a few weeks ago, but when launching in vSphere, I don't see any `vapp` properties that are user configurable.

**Comment by charandas** [comment] 2017-12-18 22:04
It also says in the [wiki](https://github.com/vmware/photon/wiki/What-is-New-in-Photon-OS-2.0#os-and-storage-management-enhancements) that `Guestinfo` interface is available for cloud-init. If so, cannot wait to play with it.

**Comment by sharathjg** [comment] 2018-04-21 00:08
The vapp properties can be explicity set using ovftool. These are not specified in the ova that we publish for 2.0.

**Comment by akutz** [comment] 2018-06-21 15:35
Hi @sharathjg,

I was about to file an issue regarding the guestinfo interface when I found this closed issue. The reason I was filing an issue is because I could not find anything related to Photon and the guestinfo interface when I googled it. Based on your feedback above, I'm still unclear to the level of support PhotonOS has for this interface. Is there documentation or a link to some code I can read? Thank you!

**Comment by akutz** [comment] 2018-06-21 15:41
Hi @sharathjg,

So I found 4018493923513ed2114fda8725b351de4a7eb725, but based on the code it doesn't seem the level of support extends to the equivalent level in CoreOS, specifically these three properties:

* `coreos.config.data`
* `coreos.confg.data.encoding`
* `coreos.config.url`

Now, obviously the above properties are specific to CoreOS, but I see no analogues in PhotonOS. The three properties above enable supplying an entire, encoded cloud-config file to the guestinfo interface in order to have it executed upon boot. Am I correct in that there is currently no like feature in PhotonOS?

**Comment by suezzelur** [comment] 2018-06-21 19:07
@akutz can you use guestinfo.userdata in base64 encoded format?

**Comment by akutz** [comment] 2018-06-21 19:12
Hi @suezzelur,

From where did you derive the property? For guestinfo documentation I've seen CoreOS (with their expanded property set) and a few other links, but nothing with `userdata`.

Also, is there some process that runs on boot that automatically inspects that property and attempts to run a config program such as cloud-init against the data? That's one of the values of what CoreOS does -- we can inject the config data into a template as is, making patching in modifications to newer versions of OVAs a thing of the past.

**Comment by suezzelur** [comment] 2018-06-21 19:19
If you enable the VmxGuestinfo datasource for cloud-init - https://github.com/vmware/photon/commit/4018493923513ed2114fda8725b351de4a7eb725#diff-450f500954d5b84ef3b3ecfbf51ed805, the new ova deployment can use the guestinfo.userdata set in the vmx file as the userdata input for cloud-init to consume.

**Comment by akutz** [comment] 2018-06-21 23:03
Hi @suezzelur,

Is there a documentation resource for this information?

**Comment by akutz** [comment] 2018-06-21 23:08
Hi @suezzelur,

I take that back. I see the userdata actually being read, but not executed. I searched this repo for `userdata` - https://github.com/vmware/photon/search?q=userdata&unscoped_q=userdata. The data is read, but it doesn't appear anything actually uses that field.

**Comment by akutz** [comment] 2018-08-07 16:58
Hi @suezzelur,

Any news on this? I cloned the repo and searched for `userdata_raw`, and as I mentioned above, I can see where the data is read, but not where anything uses that data to initialize a system:

```shell
$ grep -R userdata_raw *
SPECS/cloud-init/datasource-guestinfo.patch:+        self.userdata_raw = ''
SPECS/cloud-init/datasource-guestinfo.patch:+            self.userdata_raw = base64.b64decode(ud)
```

Thanks!

(cc @figo)

**Comment by suezzelur** [comment] 2018-08-07 18:05
@akutz We are looking into this

**Comment by akutz** [comment] 2018-08-07 18:13
Hi @suezzelur,

Thank you very much. I'm sure it's just an operator error and that I'm missing something obvious. Thank you again!

**Comment by suezzelur** [comment] 2018-08-07 21:37
@akutz I was not able to repro your issue. I passed in guestinfo.userdata in base64 format to the VM with the datasource enabled and the userdata was properly parsed by cloud-init.

**Comment by akutz** [comment] 2018-08-07 22:15
Hi @suezzelur,

I didn't attempt to reproduce it. I was only commenting that I cannot find the code path that shows how this works. That's important to me, because I may wish to extend this to support other initialization methods. Can you please indicate the code path?

**Comment by suezzelur** [comment] 2018-08-07 22:45
The code path is native to cloud-init. Somewhere in the initialization of datasources and cloud-init stages.
https://github.com/cloud-init/cloud-init/blob/be9ecc12823607b4709b64408aee137bfdfc7d01/cloudinit/sources/__init__.py
https://github.com/cloud-init/cloud-init/blob/be9ecc12823607b4709b64408aee137bfdfc7d01/cloudinit/stages.py

**Closed by suezzelur** 2018-08-07 22:45 UTC
Labels: Nice to Have

**Comment by akutz** [comment] 2018-08-07 22:49
Hi @suezzelur,

Fair enough. I'm not asking you to reopen the issue, but I am trying to figure this out. You're saying that cloud-init reads the `userdata_raw` field from some object you pass it?

**Comment by suezzelur** [comment] 2018-08-07 22:51
Yes, you can start by searching https://github.com/cloud-init/cloud-init/search?q=get_userdata_raw&unscoped_q=get_userdata_raw

**Comment by akutz** [comment] 2018-08-07 22:53
Hi @suezzelur,

Understood. I apologize for taking up your time.

**Comment by mtthlm** [comment] 2020-03-26 19:28
Finally figured it out. After reading through source code for an hour.

If you're in ESXi web console, edit your VM settings, go to `"VM Options" > "Advanced" > "Configuration Parameters" > "Edit Configuration..."`.

Add key/value parameters as such:
```
guestinfo.userdata=I2Nsb3VkLWNvbmZpZwpob3N0bmFtZTogcGhvdG9uCg==
guestinfo.userdata.encoding=base64
```

I haven't tested the following parameters, but judging from the [code](https://github.com/vmware/photon/blob/345c2b4539e20e92191bb9f1113cc43b6477617d/SPECS/cloud-init/DataSourceVMwareGuestInfo.patch#L403) the same pattern applies:
```
guestinfo.metadata=...
guestinfo.metadata.encoding=base64
guestinfo.vendordata=...
guestinfo.vendordata.encoding=base64
```
[Support encodings](https://github.com/vmware/photon/blob/345c2b4539e20e92191bb9f1113cc43b6477617d/SPECS/cloud-init/DataSourceVMwareGuestInfo.patch#L236)

Hope that helps someone. The documentation mentions:
> "..., and deploy a virtual machine running Photon OS in vSphere."
[But stops there.](https://github.com/vmware/photon/blame/345c2b4539e20e92191bb9f1113cc43b6477617d/docs/photon_admin/deploy_photon_with_cloud-init.md#L29)

You would think VMWare of all people would make sure their documentation covered support for their products...

**Comment by akutz** [comment] 2020-03-26 19:36
To be fair, Photon OS was recently updated to use the [VMware Cloud-Init Datasource for GuestInfo](https://github.com/vmware/cloud-init-vmware-guestinfo). Those properties were not respected until recently.

**Comment by mtthlm** [comment] 2020-03-26 19:37
@akutz  🤦‍♂ Got it. It's all right there in the README. I should have looked a little harder it seems. Thanks.

**Comment by suezzelur** [comment] 2020-03-26 19:38
@mtthlm @akutz we will update the documentation to point to https://github.com/vmware/cloud-init-vmware-guestinfo repo

**Comment by akutz** [comment] 2020-03-26 19:40
> @akutz 🤦‍♂ Got it. It's all right there in the README. I should have looked a little harder it seems. Thanks.

Not at all. It is a separate repository and you would have to know about it in the first place. I also had the same questions as you two years ago, and that is what prompted me to create the new datasource in the first place. A DS that would use the standard cloud-init network configuration and other properties.
