### ISSUE TITLE
Photon 2.0 - EFI Out of memory

### ISSUE THREAD

**Issue by muhfugen** [vmware/photon#720] opened 2017-12-18 02:03 UTC
If you create a Photon 2.0 VM with the `linux` kernel, and EFI boot, and assign it 128MB of memory, upon startup it will state it is out of memory, however after a few seconds it will continue the boot process and seemingly work fine. This does not happen if it has 256MB of memory, nor does it happen if you use a legacy BIOS instead of EFI.

What exactly is it doing so early in the boot process which requires so much memory? And what is the impact of assigning it small amounts, besides a delayed boot process? Can anything be done to resolve this besides assigning it more memory?

**Comment by YustasSwamp** [comment] 2017-12-18 21:23
Do you use an ISO to install? or efi-ova image import?

**Comment by muhfugen** [comment] 2017-12-18 21:26
@YustasSwamp I used a minimal ISO install. The host is running ESXi 6.5 5969303

**Comment by YustasSwamp** [comment] 2017-12-19 05:29
ISO Installer requires more then 128MB memory to properly work.
Our recommendation is 256MB.
The main memory consumer is rootfs with installer code (python) which is located in a RAM disk.
At early boot time there are other consumers loaded together with a RAM disk:
EFI image, grub, compressed kernel, compressed RAM disk,  uncompressed kernel. First 4 will disappear only after kernel boot.

Ova image can be imported and VM memory set to 128 MB and it will work.
But ISO installer needs twice more memory.

Close the issue as not a bug.
Thanks.

**Closed by YustasSwamp** 2017-12-19 05:29 UTC

**Comment by muhfugen** [comment] 2017-12-19 06:01
@YustasSwamp 

The installer isnt relevant. During the initial install the memory was left at 2GB iirc. It was lowered to 128MB after the install.

**Comment by YustasSwamp** [comment] 2017-12-19 06:50
I'll try that

**Comment by YustasSwamp** [comment] 2017-12-19 07:08
Got it. "Error: out of memory" message from the Grub.
That means, some of operations which require extra memory were failed. and grub instead of panic just continues to work.
Specifically in my case, initrd was not loaded.

The difference between BIOS and EFI.
In the first case, grub controls available memory by itself.
in the second case, grub asks EFI to allocate a memory. And looks like EFI firmware is more restrictive when the system is low on memory.
