### ISSUE TITLE
Photon Repos Disabled?

### ISSUE THREAD

**Issue by vampire337** [vmware/photon#1096] opened 2021-01-15 00:20 UTC
Just trying to update a VM that I haven't touched in some months, and it seems the repos are down?

`tdnf distro-sync`
`Refreshing metadata for: 'VMware Photon Linux 3.0(x86_64)'
Error: 401 when downloading https://dl.bintray.com/vmware/photon_release_3.0_x86_64/repodata/repomd.xml
. Please check repo url.
Error: Failed to synchronize cache for repo 'VMware Photon Linux 3.0(x86_64)' from 'https://dl.bintray.com/vmware/photon_release_3.0_x86_64'
Disabling Repo: 'VMware Photon Linux 3.0(x86_64)'
Refreshing metadata for: 'VMware Photon Extras 3.0(x86_64)'
Error: 401 when downloading https://dl.bintray.com/vmware/photon_extras_3.0_x86_64/repodata/repomd.xml
. Please check repo url.
Error: Failed to synchronize cache for repo 'VMware Photon Extras 3.0(x86_64)' from 'https://dl.bintray.com/vmware/photon_extras_3.0_x86_64'
Disabling Repo: 'VMware Photon Extras 3.0(x86_64)'
Refreshing metadata for: 'VMware Photon Linux 3.0(x86_64) Updates'
Error: 404 when downloading https://dl.bintray.com/vmware/photon_updates_3.0_x86_64/repodata/repomd.xml
. Please check repo url.
Error: Failed to synchronize cache for repo 'VMware Photon Linux 3.0(x86_64) Updates' from 'https://dl.bintray.com/vmware/photon_updates_3.0_x86_64'
Disabling Repo: 'VMware Photon Linux 3.0(x86_64) Updates'
Nothing to do.
`

I have tried tdnf clean all and tdnf makecache with similar failures. https://dl.bintray.com/vmware/photon_updates_3.0_x86_64 in a web browser returns "Repository path missing or not specified."

**Comment by vampire337** [comment] 2021-01-15 00:21
https://github.com/vmware/photon/issues/849 might have been the same issue, but I've opened this new issue in case it's something entirely different.

**Comment by ssahani** [comment] 2021-01-15 03:21
Duplicate of https://github.com/vmware/photon/issues/1074

**Comment by ssahani** [comment] 2021-02-16 13:01
Closing

**Closed by ssahani** 2021-02-16 13:01 UTC
Labels: tdnf
