### ISSUE TITLE
Photon 3.0 - default gateway from DHCP

### ISSUE THREAD

**Issue by MikeVL** [vmware/photon#885] opened 2019-03-24 18:39 UTC
After upgrade to photon v3.0 default gateway is not set from DHCP config.

```shell
root@photon-machine ➜  cat /etc/systemd/network/99-dhcp-en.network
[Match]
Name=e*

[Network]
DHCP=yes
IPv6AcceptRA=no

root@photon-machine ➜  route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
10.0.0.0        10.77.1.1       255.0.0.0       UG    1024   0        0 eth0
10.77.1.0       0.0.0.0         255.255.255.0   U     0      0        0 eth0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
```

**Comment by jodumont** [comment] 2019-04-05 19:00
@MikeVL on which provider ?

**Comment by MikeVL** [comment] 2019-04-05 19:02
DHCP server in Windows Server 2016

**Comment by MikeVL** [comment] 2019-04-09 14:00
Photon v2.0
```
Apr 09 13:51:50 photon-v2 cloud-init[291]: Cloud-init v. 0.7.9 running 'init' at Tue, 09 Apr 2019 13:51:38 +0000. Up 18.38 seconds.
Apr 09 13:51:50 photon-v2 cloud-init[291]: ci-info: ++++++++++++++++++++++++++++++++++++++Net device info++++++++++++++++++++++++++++++++++++++
Apr 09 13:51:50 photon-v2 cloud-init[291]: ci-info: +--------+------+-----------------------------+---------------+-------+-------------------+
Apr 09 13:51:50 photon-v2 cloud-init[291]: ci-info: | Device |  Up  |           Address           |      Mask     | Scope |     Hw-Address    |
Apr 09 13:51:50 photon-v2 cloud-init[291]: ci-info: +--------+------+-----------------------------+---------------+-------+-------------------+
Apr 09 13:51:50 photon-v2 cloud-init[291]: ci-info: |  eth0  | True |         10.77.1.163         | 255.255.255.0 |   .   | 00:50:56:a8:fa:1b |
Apr 09 13:51:50 photon-v2 cloud-init[291]: ci-info: |  eth0  | True | fe80::250:56ff:fea8:fa1b/64 |       .       |  link | 00:50:56:a8:fa:1b |
Apr 09 13:51:50 photon-v2 cloud-init[291]: ci-info: |   lo   | True |          127.0.0.1          |   255.0.0.0   |   .   |         .         |
Apr 09 13:51:50 photon-v2 cloud-init[291]: ci-info: |   lo   | True |           ::1/128           |       .       |  host |         .         |
Apr 09 13:51:50 photon-v2 cloud-init[291]: ci-info: +--------+------+-----------------------------+---------------+-------+-------------------+
Apr 09 13:51:50 photon-v2 cloud-init[291]: ci-info: +++++++++++++++++++++++++++++Route IPv4 info+++++++++++++++++++++++++++++
Apr 09 13:51:50 photon-v2 cloud-init[291]: ci-info: +-------+-------------+-----------+-----------------+-----------+-------+
Apr 09 13:51:50 photon-v2 cloud-init[291]: ci-info: | Route | Destination |  Gateway  |     Genmask     | Interface | Flags |
Apr 09 13:51:50 photon-v2 cloud-init[291]: ci-info: +-------+-------------+-----------+-----------------+-----------+-------+
Apr 09 13:51:50 photon-v2 cloud-init[291]: ci-info: |   0   |   0.0.0.0   | 10.77.1.1 |     0.0.0.0     |    eth0   |   UG  |
Apr 09 13:51:50 photon-v2 cloud-init[291]: ci-info: |   1   |   10.0.0.0  | 10.77.1.1 |    255.0.0.0    |    eth0   |   UG  |
Apr 09 13:51:50 photon-v2 cloud-init[291]: ci-info: |   2   |  10.77.1.0  |  0.0.0.0  |  255.255.255.0  |    eth0   |   U   |
Apr 09 13:51:50 photon-v2 cloud-init[291]: ci-info: |   3   |  10.77.1.1  |  0.0.0.0  | 255.255.255.255 |    eth0   |   UH  |
Apr 09 13:51:50 photon-v2 cloud-init[291]: ci-info: +-------+-------------+-----------+-----------------+-----------+-------+
```
Photon v3.0
```
Apr 09 13:35:21 photon-machine cloud-init[238]: Cloud-init v. 18.3 running 'init' at Tue, 09 Apr 2019 13:35:21 +0000. Up 7.69 seconds.
Apr 09 13:35:21 photon-machine cloud-init[238]: ci-info: ++++++++++++++++++++++++++++++++++++++Net device info+++++++++++++++++++++++++++++++++++++++
Apr 09 13:35:21 photon-machine cloud-init[238]: ci-info: +--------+------+-----------------------------+---------------+--------+-------------------+
Apr 09 13:35:21 photon-machine cloud-init[238]: ci-info: | Device |  Up  |           Address           |      Mask     | Scope  |     Hw-Address    |
Apr 09 13:35:21 photon-machine cloud-init[238]: ci-info: +--------+------+-----------------------------+---------------+--------+-------------------+
Apr 09 13:35:21 photon-machine cloud-init[238]: ci-info: |  eth0  | True |         10.77.1.155         | 255.255.255.0 | global | 00:50:56:a8:d6:2c |
Apr 09 13:35:21 photon-machine cloud-init[238]: ci-info: |  eth0  | True | fe80::250:56ff:fea8:d62c/64 |       .       |  link  | 00:50:56:a8:d6:2c |
Apr 09 13:35:21 photon-machine cloud-init[238]: ci-info: |   lo   | True |          127.0.0.1          |   255.0.0.0   |  host  |         .         |
Apr 09 13:35:21 photon-machine cloud-init[238]: ci-info: |   lo   | True |           ::1/128           |       .       |  host  |         .         |
Apr 09 13:35:21 photon-machine cloud-init[238]: ci-info: +--------+------+-----------------------------+---------------+--------+-------------------+
Apr 09 13:35:21 photon-machine cloud-init[238]: ci-info: ++++++++++++++++++++++++++++Route IPv4 info++++++++++++++++++++++++++++
Apr 09 13:35:21 photon-machine cloud-init[238]: ci-info: +-------+-------------+-----------+---------------+-----------+-------+
Apr 09 13:35:21 photon-machine cloud-init[238]: ci-info: | Route | Destination |  Gateway  |    Genmask    | Interface | Flags |
Apr 09 13:35:21 photon-machine cloud-init[238]: ci-info: +-------+-------------+-----------+---------------+-----------+-------+
Apr 09 13:35:21 photon-machine cloud-init[238]: ci-info: |   0   |   10.0.0.0  | 10.77.1.1 |   255.0.0.0   |    eth0   |   UG  |
Apr 09 13:35:21 photon-machine cloud-init[238]: ci-info: |   1   |  10.77.1.0  |  0.0.0.0  | 255.255.255.0 |    eth0   |   U   |
Apr 09 13:35:21 photon-machine cloud-init[238]: ci-info: +-------+-------------+-----------+---------------+-----------+-------+
Apr 09 13:35:21 photon-machine cloud-init[238]: ci-info: +++++++++++++++++++Route IPv6 info+++++++++++++++++++
Apr 09 13:35:21 photon-machine cloud-init[238]: ci-info: +-------+-------------+---------+-----------+-------+
Apr 09 13:35:21 photon-machine cloud-init[238]: ci-info: | Route | Destination | Gateway | Interface | Flags |
Apr 09 13:35:21 photon-machine cloud-init[238]: ci-info: +-------+-------------+---------+-----------+-------+
Apr 09 13:35:21 photon-machine cloud-init[238]: ci-info: |   1   |  fe80::/64  |    ::   |    eth0   |   U   |
Apr 09 13:35:21 photon-machine cloud-init[238]: ci-info: |   3   |    local    |    ::   |    eth0   |   U   |
Apr 09 13:35:21 photon-machine cloud-init[238]: ci-info: |   4   |   ff00::/8  |    ::   |    eth0   |   U   |
Apr 09 13:35:21 photon-machine cloud-init[238]: ci-info: +-------+-------------+---------+-----------+-------+
Apr 09 13:35:21 photon-machine cloud-init[238]: 2019-04-09 13:35:21,961 - warnings.py[WARNING]: **************************************************************************
Apr 09 13:35:21 photon-machine cloud-init[238]: # A new feature in cloud-init identified possible datasources for        #
Apr 09 13:35:21 photon-machine cloud-init[238]: # this system as:                                                        #
Apr 09 13:35:21 photon-machine cloud-init[238]: #   []                                                                   #
Apr 09 13:35:21 photon-machine cloud-init[238]: # However, the datasource used was: None                                 #
Apr 09 13:35:21 photon-machine cloud-init[238]: #                                                                        #
Apr 09 13:35:21 photon-machine cloud-init[238]: # In the future, cloud-init will only attempt to use datasources that    #
Apr 09 13:35:21 photon-machine cloud-init[238]: # are identified or specifically configured.                             #
Apr 09 13:35:21 photon-machine cloud-init[238]: # For more information see                                               #
Apr 09 13:35:21 photon-machine cloud-init[238]: #   https://bugs.launchpad.net/bugs/1669675                              #
Apr 09 13:35:21 photon-machine cloud-init[238]: #                                                                        #
Apr 09 13:35:21 photon-machine cloud-init[238]: # If you are seeing this message, please file a bug against              #
Apr 09 13:35:21 photon-machine cloud-init[238]: # cloud-init at                                                          #
Apr 09 13:35:21 photon-machine cloud-init[238]: #    https://bugs.launchpad.net/cloud-init/+filebug?field.tags=dsid      #
Apr 09 13:35:21 photon-machine cloud-init[238]: # Make sure to include the cloud provider your instance is               #
Apr 09 13:35:21 photon-machine cloud-init[238]: # running on.                                                            #
Apr 09 13:35:21 photon-machine cloud-init[238]: #                                                                        #
Apr 09 13:35:21 photon-machine cloud-init[238]: # After you have filed a bug, you can disable this warning by launching  #
Apr 09 13:35:21 photon-machine cloud-init[238]: # your instance with the cloud-config below, or putting that content     #
Apr 09 13:35:21 photon-machine cloud-init[238]: # into /etc/cloud/cloud.cfg.d/99-warnings.cfg                            #
Apr 09 13:35:21 photon-machine cloud-init[238]: #                                                                        #
Apr 09 13:35:21 photon-machine cloud-init[238]: # #cloud-config                                                          #
Apr 09 13:35:21 photon-machine cloud-init[238]: # warnings:                                                              #
Apr 09 13:35:21 photon-machine cloud-init[238]: #   dsid_missing_source: off                                             #
Apr 09 13:35:21 photon-machine cloud-init[238]: **************************************************************************
Apr 09 13:35:22 photon-machine systemd-networkd[185]: DHCPv6 CLIENT: Sent INFORMATION-REQUEST
Apr 09 13:35:22 photon-machine systemd-networkd[185]: DHCPv6 CLIENT: Next retransmission in 1s

**Comment by MikeVL** [comment] 2019-04-10 05:53
DHCP works:
![Снимок экрана 2019-04-10 в 8 48 31](https://user-images.githubusercontent.com/118285/55854556-b6538300-5b6d-11e9-91ab-fd2827edb073.jpg)

New IP from DHCP 
![Снимок экрана 2019-04-10 в 8 51 25](https://user-images.githubusercontent.com/118285/55854594-d8e59c00-5b6d-11e9-9914-06c32110e663.jpg)

Logs:
```
Apr 10 05:48:49 photon-v3 systemd-networkd[185]: DHCP CLIENT (0x9cc9d6e1): STARTED on ifindex 2
Apr 10 05:48:49 photon-v3 systemd-networkd[185]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=8 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Apr 10 05:48:49 photon-v3 systemd-networkd[185]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=9 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Apr 10 05:48:49 photon-v3 systemd-networkd[185]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=10 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Apr 10 05:48:49 photon-v3 systemd-networkd-wait-online[187]: ignoring: lo
Apr 10 05:48:49 photon-v3 systemd-networkd[185]: DHCP CLIENT (0x9cc9d6e1): DISCOVER
Apr 10 05:48:49 photon-v3 systemd-networkd[185]: DHCP CLIENT (0x9cc9d6e1): OFFER
Apr 10 05:48:49 photon-v3 systemd-networkd[185]: DHCP CLIENT (0x9cc9d6e1): REQUEST (requesting)
Apr 10 05:48:49 photon-v3 systemd-networkd[185]: DHCP CLIENT (0x9cc9d6e1): ACK
Apr 10 05:48:49 photon-v3 systemd-networkd[185]: DHCP CLIENT (0x9cc9d6e1): lease expires in 4d 23h 59min 58s
Apr 10 05:48:49 photon-v3 systemd-networkd[185]: DHCP CLIENT (0x9cc9d6e1): T2 expires in 4d 8h 59min 58s
Apr 10 05:48:49 photon-v3 systemd-networkd[185]: DHCP CLIENT (0x9cc9d6e1): T1 expires in 2d 11h 59min 57s
Apr 10 05:48:49 photon-v3 systemd-networkd[185]: eth0: DHCPv4 address 10.77.1.165/24 via 10.77.1.1
Apr 10 05:48:49 photon-v3 systemd-networkd[185]: eth0: Updating address: 10.77.1.165/24 (valid for 5d)

```

**Comment by ssahani** [comment] 2019-04-10 07:24
When networkd receives some routes it logs something like this.
```
veth-test: DHCPv4 address 192.168.5.31/24 via 192.168.5.1
veth-test: Updating address: 192.168.5.31/24 (valid for 1h)
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_314 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=41 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
veth-test: Adding route: dst: 192.168.5.31/32, src: n/a, gw: n/a, prefsrc: 192.168.5.31
veth-test: Adding route: dst: 192.168.5.255/32, src: n/a, gw: n/a, prefsrc: 192.168.5.31
veth-test: Adding route: dst: 192.168.5.0/24, src: n/a, gw: n/a, prefsrc: 192.168.5.31
veth-test: Adding route: dst: 192.168.5.0/32, src: n/a, gw: n/a, prefsrc: 192.168.5.31
veth-test: DHCP: No routes received from DHCP server: No data available
veth-test: Configuring route: dst: 192.168.5.1/32, src: n/a, gw: n/a, prefsrc: 192.168.5.31
veth-test: Configuring route: dst: n/a, src: n/a, gw: 192.168.5.1, prefsrc: 192.168.5.31
veth-test: Updating route: dst: 192.168.5.1/32, src: n/a, gw: n/a, prefsrc: 192.168.5.31
veth-test: Updating route: dst: n/a, src: n/a, gw: 192.168.5.1, prefsrc: 192.168.5.31
veth-test: Configured
```

My test conf

```
[root@Zeus network]# cat 12-veth.netdev
[NetDev]
Name=veth-test
Kind=veth

[Peer]
Name=veth-peer
[root@Zeus network]# cat veth0.network
[Match]
Name=veth-test

[Network]
DHCP=ipv4
IPv6AcceptRA=false
[root@Zeus network]# cat veth0-peer.network
[Match]
Name=veth-peer

[Network]
Address=192.168.5.1/24
IPv6AcceptRA=false
DHCPServer=yes

[DHCPServer]
PoolOffset=10
PoolSize=50
DNS=192.168.5.1
NTP=192.168.5.1
[root@Zeus network]#
```

```
# ip route                                                                                                                                         
default via 192.168.5.1 dev veth-test proto dhcp src 192.168.5.31 metric 1024 
```

Can you see these logs ?

**Comment by MikeVL** [comment] 2019-04-10 08:22
Set default gateway 10.77.1.1 ?
```
Apr 10 05:48:49 photon-v3 systemd-networkd[185]: eth0: DHCPv4 address 10.77.1.165/24 via 10.77.1.1``

All the vm in my infrastructure works well with DHCP server, only Photon v3.0 does not set the default gateway.

**Comment by ssahani** [comment] 2019-04-10 08:41
yes that makes sense. This message says you have received the default route but setting routes logs are missing .  

In the ```[DHCP]``` section if ```UseRoutes=``` is false then we won't be able to see these logs. But by default it's true.   

See https://www.freedesktop.org/software/systemd/man/systemd.network.html#UseRoutes=

I can't reproduce this in upstream though.

**Comment by MikeVL** [comment] 2019-04-10 10:29
My DHCP had option 121 (static routes), if i remove this option, default gateway will set.

![Снимок экрана 2019-04-10 в 13 27 47](https://user-images.githubusercontent.com/118285/55871999-8ff50e00-5b94-11e9-8016-2a4c35db9022.jpg)

**Comment by ssahani** [comment] 2019-04-10 10:50
Ahhh right according to RFC 3442: If the DHCP server returns both a Classless Static Routes option and
a Router option, the DHCP client MUST ignore the Router option.

See https://tools.ietf.org/html/rfc3442 section DHCP Client Behavior.

**Comment by ssahani** [comment] 2019-04-10 10:51
BTW I failed to parse what written in Russian :)

**Comment by MikeVL** [comment] 2019-04-10 10:56
Hm, why Photon v2.0 and other clients works well with option 121 Classless Static Routes?

**Comment by ssahani** [comment] 2019-04-10 11:01
That was a bug . We fixed that upstream .

See https://github.com/systemd/systemd/commit/a9381b7c6cc6aaecdef454a207a56b71a83511e8
https://github.com/systemd/systemd/issues/5695

**Comment by MikeVL** [comment] 2019-04-10 11:05
After add default gateway to option 121, photon v3.0 is ok.

But now on photon v2.0 default gateway set twice.
![Снимок экрана 2019-04-10 в 14 00 47](https://user-images.githubusercontent.com/118285/55873984-b8333b80-5b99-11e9-9c3e-7c01da1736c8.jpg)

**Comment by ssahani** [comment] 2019-04-10 11:13
That patch I mentioned to be backported.

**Comment by ssahani** [comment] 2019-04-10 16:46
@MikeVL Can we close this . Feel free to open a new issue to backport the issue I mentioned.

**Closed** 2019-04-10 16:46 UTC
