### ISSUE TITLE
nginx package broken

### ISSUE THREAD

**Issue by casualjim** [vmware/photon#486] opened 2016-07-04 17:00 UTC
# Problem 1: non-existing run state dir

when I do 

```
tdnf install -y nginx
reboot
systemctl start nginx
```

nginx doesn't start because /var/run/nginx doesn't exist.

# Problem 2: /etc/hosts ordering or default nginx.conf

the order in /etc/hosts makes ipv6 preferred, but nginx isn't configured to use ipv6, so this happens

```
root@ivan-test [ ~ ]# cat /etc/hosts
# Begin /etc/hosts (network card version)

::1         localhost ipv6-localhost ipv6-loopback
127.0.0.1   localhost.localdomain
127.0.0.1	localhost
127.0.0.1	ivan-test
# End /etc/hosts (network card version)
root@ivan-test [ ~ ]# curl localhost
curl: (7) Failed to connect to localhost port 80: Connection refused
```

changing the ordering in /etc/hosts makes this work

```
root@ivan-test [ ~ ]# cat /etc/hosts
# Begin /etc/hosts (network card version)

127.0.0.1	localhost
::1         localhost ipv6-localhost ipv6-loopback
127.0.0.1   localhost.localdomain
127.0.0.1	ivan-test
# End /etc/hosts (network card version)
root@ivan-test [ ~ ]# curl -s localhost | head -n3
<!DOCTYPE html>
<html>
<head>
```

Or changing the default nginx config

added this to my nginx config:

```
listen [::]:80;
```

then I can use the default hosts config too:

```
root@ivan-test [ ~ ]# cat /etc/hosts
# Begin /etc/hosts (network card version)

::1         localhost ipv6-localhost ipv6-loopback
127.0.0.1   localhost.localdomain
127.0.0.1	localhost
127.0.0.1	ivan-test
# End /etc/hosts (network card version)
root@ivan-test [ ~ ]# curl -s localhost | head -n3
<!DOCTYPE html>
<html>
<head>
```

**Comment by dthaluru** [comment] 2016-07-08 18:30
@casualjim  I was not able to reproduce the issue in Photon OS 1.0 GA version (flavor minimal).
In which version of Photon OS are you seeing this issue?

**Comment by casualjim** [comment] 2016-07-08 18:37
Photon 1.0 GA is the version I'm using, and I start with a minimal install. I think I did this on an esx server

**Comment by dthaluru** [comment] 2016-07-08 19:34
I was able to reproduce Problem2 but I was not able to reproduce Problem1.

We create directory /var/run/nginx during nginx rpm installation. Please check if you have right version of PhotonOS. Can you share build number specified in /etc/photon-release file?

https://github.com/vmware/photon/blob/1.0/SPECS/nginx/nginx.spec#L67

**Comment by casualjim** [comment] 2016-07-08 20:53
hi I was able to run into this on my local fusion too.  I took the photon iso and did a plain vanilla minimal install. Opened up ssh for root and restarted sshd.

```shellsession
root@ivan-test [ ~ ]# cat /etc/photon-release
VMware Photon Linux 1.0
PHOTON_BUILD_NUMBER=13c08b6
```

session
```shellsession
± ivan@aether:~/go/src/github.com/vmware/cello
git:(publish-cello-daemon) ✗ ? » ssh root@172.16.202.139
Password:
root@ivan-test [ ~ ]# tdnf makecache
Refreshing metadata for: 'VMware Photon Linux 1.0(x86_64)Updates'
Refreshing metadata for: 'VMware Photon Extras 1.0(x86_64)'
Refreshing metadata for: 'VMware Photon Linux 1.0(x86_64)'
Refreshing metadata for: 'VMware Lightwave 1.0(x86_64)'
Metadata cache created.
root@ivan-test [ ~ ]# tdnf install -y nginx

Installing:
nginx                                               x86_64             1.10.0-2.ph1                           5.38 M

Total installed size: 5.38 M

Downloading:
nginx                                  2599804    100%
Testing transaction
Running transaction

Complete!
root@ivan-test [ ~ ]# reboot
Connection to 172.16.202.139 closed by remote host.
Connection to 172.16.202.139 closed.
± ivan@aether:~/go/src/github.com/vmware/cello
git:(publish-cello-daemon) ✗ ? » ssh root@172.16.202.139
Password:
Last login: Fri Jul  8 20:48:14 2016 from 172.16.202.1
root@ivan-test [ ~ ]# systemctl start nginx
Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.
root@ivan-test [ ~ ]# journalctl -xe --unit nginx
-- Logs begin at Fri 2016-07-08 20:23:36 UTC, end at Fri 2016-07-08 20:49:21 UTC. --
Jul 08 20:49:21 ivan-test systemd[1]: Starting Nginx High-performance HTTP server and reverse proxy...
-- Subject: Unit nginx.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit nginx.service has begun starting up.
Jul 08 20:49:21 ivan-test nginx[811]: nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
Jul 08 20:49:21 ivan-test nginx[811]: nginx: [emerg] open() "/var/run/nginx/nginx.pid" failed (2: No such file or directory)
Jul 08 20:49:21 ivan-test nginx[811]: nginx: configuration file /etc/nginx/nginx.conf test failed
Jul 08 20:49:21 ivan-test systemd[1]: nginx.service: Control process exited, code=exited status=1
Jul 08 20:49:21 ivan-test systemd[1]: Failed to start Nginx High-performance HTTP server and reverse proxy.
-- Subject: Unit nginx.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit nginx.service has failed.
--
-- The result is failed.
Jul 08 20:49:21 ivan-test systemd[1]: nginx.service: Unit entered failed state.
Jul 08 20:49:21 ivan-test systemd[1]: nginx.service: Failed with result 'exit-code'.
root@ivan-test [ ~ ]#
```

**Comment by casualjim** [comment] 2016-07-08 22:00
You have to reboot because the issue is:

The /run is mounted as tmpfs

```
root@ivan-test [ ~ ]# mount | grep /run
tmpfs on /run type tmpfs (rw,nosuid,nodev,mode=755)
tmpfs on /run/user/0 type tmpfs (rw,nosuid,nodev,relatime,size=402876k,mode=700)
```
and /var/run is a link to ../run

```
root@ivan-test [ ~ ]# ls -l /var | grep run
lrwxrwxrwx  1 root root   11 Jul  8 20:22 lock -> ../run/lock
lrwxrwxrwx  1 root root    6 Jul  8 20:23 run -> ../run
```

So when you reboot the system clears the tmpfs items and so when photon is rebooted /var/run/nginx no longer exists.

a simple solution would be to not use /var/run/nginx/nginx.pid but /var/run/nginx.pid

**Comment by dthaluru** [comment] 2016-07-08 22:06
I am able to reproduce the issue. Fix is inflight.

**Comment by dthaluru** [comment] 2016-07-20 17:48
Fix is merged in dev branch. Commit 69690e7 (address problem1) and commit 3d53bdd (address problem2).

**Closed by dthaluru** 2016-07-20 17:48 UTC
