### ISSUE TITLE
upgrading 4.0 #d98e681 to #1526e30

### ISSUE THREAD

**Issue by somedevreally** [vmware/photon#1169] opened 2021-03-23 21:52 UTC
Hello,

am on Esxi with Photon 4.0 build #d98e681 and trying to upgrade to build #1526e30
when i try upgrade command 
```
# tdnf -y install photon-upgrade
photon-upgrade package not found or not installed
Error(1011) : No matching packages
```
i tried these command to upgrade and it says Nothing to do.

```
# tdnf upgrade tdnf
Nothing to do.
# tdnf upgrade -y
Nothing to do.
```

thanks

**Comment by suezzelur** [comment] 2021-03-23 22:00
photon-upgrade is for release to release upgrade (e.g. from 3.0 to 4.0). For in release upgrades, you can use tdnf distro-sync.

**Comment by somedevreally** [comment] 2021-03-23 22:03
thanks for quick reply.
now i get this error
```
#tdnf distro-sync

Removing:
systemd-udev      x86_64   247.2-2.ph4 @System    8.45M 8863168

Total installed size:   8.45M 8863168
Is this ok [y/N]: y
Found 2 problems
systemd-udev is needed by (installed) minimal-0.1-4.ph4.x86_64
Testing transaction
Error(1525) : rpm transaction failed
```

**Comment by suezzelur** [comment] 2021-03-23 22:04
@ssahani

**Comment by ssahani** [comment] 2021-03-24 08:57
It's duplicate of https://github.com/vmware/photon/issues/1127

Here is the solution
https://github.com/vmware/photon/issues/1127#issuecomment-795255936

**Comment by somedevreally** [comment] 2021-03-24 13:17
thanks @ssahani, i was able to  reinstall systemd-udev-247.3-1.ph4
now i tried upgrading it says nothing to do, does it take time?
```
# tdnf distro-sync
Nothing to do.
```

**Comment by ssahani** [comment] 2021-03-24 13:34
We fixed it  in https://github.com/vmware/photon/commit/48433fdd4b53a487f87d68ea8e356bf788dd66bc#diff-dbb1dfec7bad951157ae5dcdcf6bd7aa847c1eafe9e22ca6b516fe050019c632.   New packages has not been published yet though. Thanks for you patience.

**Comment by ssahani** [comment] 2021-03-24 14:05
Closing then .

**Closed by ssahani** 2021-03-24 14:05 UTC
