### ISSUE TITLE
After upgrade photon is not booting

### ISSUE THREAD

**Issue by MikeVL** [vmware/photon#802] opened 2018-08-23 06:59 UTC
After upgrade packages, got error

Booting photon:
Error: not a regular file.

![2018-08-23 9 58 42](https://user-images.githubusercontent.com/118285/44509738-31d5f200-a6bb-11e8-946a-d24db295aa81.jpg)

**Comment by jnovack** [comment] 2018-08-30 15:57
uh oh, something is a link or a directory when it should be a file.

Do you have any diagnostics?  Can you mount the VM HD in another VM?

**Comment by MikeVL** [comment] 2018-08-30 16:54
Yes, i can mount HD to another VM

**Comment by MikeVL** [comment] 2018-08-31 09:47
I found broken link from photon.cfg to old linux-4.9.99-1.ph2-esx.cfg

**Comment by srivatsabhat** [comment] 2018-09-21 20:11
Hi @MikeVL 

Can you reproduce this issue? Do you remember which kernel versions you were updating from and to? Also, did you change kernel flavors by any chance (linux-esx vs linux etc)? Did you happen to abort package updates or did you have any errors during the update?

**Comment by YustasSwamp** [comment] 2018-12-17 22:39
By symptoms, looks like you did force reboot right after upgrade and files haven't reach the disk.

**Comment by srivatsabhat** [comment] 2019-01-15 23:14
Closing this, as we don't have sufficient info to debug further. Please reopen if you encounter this issue again.

**Closed by srivatsabhat** 2019-01-15 23:14 UTC
